/* cSpell:words VSRP KNOCKBACK unsubs targetable Oakhaven Torvald Malakor catacomb Cataclysm miasma portcullis */
/**
 * ============================================================================
 * EMBERLIGHT SOVEREIGN ENGINE: DECLARATIVE STATIC DATA MANIFEST
 * Document Identifier: VSRP-001-DATA-MANIFEST
 * Governing Protocol:  VSRP-001 / ARCH-SPEC-MANIFEST-001
 * Authority:           Host SSOT
 * Timestamp:           2026-09-06T20:25:30Z
 * Index Anchor:        PRS-001
 * ============================================================================
 *
 * TABLE OF CONTENTS & NAVIGATION ANCHORS:
 *   [SEC-00] Domain Type Contracts & JSDoc Definitions
 *   [SEC-01] Engine Settings & Operational Tuning Profile
 *   [SEC-02] Session Baseline & Exploration Configuration
 *   [SEC-03] Party Roster, Phenotypes & Stat Growth Curves
 *   [SEC-04] Item Catalog, Equipment & Relic Artifacts
 *   [SEC-05] Bestiary Registry & Tactical Encounter Tables
 *   [SEC-06] Aether Matrix Constellation & Essence Graph
 *   [SEC-07] Archetype Progression Skill Trees
 *   [SEC-08] Spatial Tile Legend & World Topology Maps
 *   [SEC-09] Status Ailments, Quest Journal & Map Mutations
 *   [SEC-10] Commercial Shops & Scripted Branching Dialogues
 *   [SEC-11] Domain Stat Calculators & Projection Kernels
 *   [SEC-12] Immutability Sealing & Runtime Module Exports
 * ============================================================================
 */

//#region [SEC-00] Domain Type Contracts & JSDoc Definitions

/**
 * @typedef {Object} BaseStats
 * @property {number} hp - Base vitality / maximum hit points.
 * @property {number} mp - Base mana / maximum mana pool.
 * @property {number} atk - Base physical/magical strike offensive rating.
 * @property {number} def - Base armor / physical mitigation score.
 * @property {number} agi - Base agility / action pacing rate.
 */

/**
 * @typedef {Object} CharacterStats
 * @property {number} hp - Current calculated hit points.
 * @property {number} maxHp - Authoritative maximum hit point ceiling.
 * @property {number} mp - Current calculated mana points.
 * @property {number} maxMp - Authoritative maximum mana ceiling.
 * @property {number} atk - Effective attack rating.
 * @property {number} def - Effective physical mitigation defense.
 * @property {number} agi - Effective action pacing agility.
 * @property {Record<string, number>} [affinities] - Elemental defense affinities.
 */

/**
 * @typedef {Object} CharacterEquipment
 * @property {string|null} [weapon] - Item identifier equipped to weapon slot.
 * @property {string|null} [armor] - Item identifier equipped to armor slot.
 * @property {string|null} [accessory] - Item identifier equipped to accessory slot.
 */

/**
 * @typedef {Object} CharacterSnapshot
 * @property {string} [id] - Unique runtime instance identifier.
 * @property {string} [instanceId] - Alternative roster identity key.
 * @property {string} name - Display label of character.
 * @property {'HERO'|'WARRIOR'|'MAGE'|'HEALER'} phenotype - Canonical phenotype archetype.
 * @property {number} [level] - Current character progression tier.
 * @property {number} [hp] - Transient current health value.
 * @property {number} [maxHp] - Transient maximum health value.
 * @property {number} [mp] - Transient current mana value.
 * @property {number} [maxMp] - Transient maximum mana value.
 * @property {CharacterEquipment} [equipment] - Currently equipped item mapping.
 * @property {string[]} [unlockedNodes] - Array of unlocked Aether matrix node identifiers.
 * @property {string[]} [unlocked] - Legacy alias for unlocked node array.
 * @property {number} [skillPoints] - Total skill points allocated.
 * @property {number} [unspentSP] - Remaining unspent skill points.
 */

/**
 * @typedef {Object} ItemDefinition
 * @property {string} id - Unique catalog item token.
 * @property {string} label - Display label.
 * @property {string} desc - Sensory description and telemetry summary.
 * @property {number} cost - Commercial purchase price in gold units.
 * @property {'weapon'|'armor'|'accessory'} [slot] - Target equipment paper-doll slot.
 * @property {'ally_alive'|'ally_dead'|'enemy'} [targetType] - Operational activation target rule.
 * @property {Partial<BaseStats & { level: number }>} [requirements] - Prerequisite stats to equip.
 * @property {Array<'HERO'|'WARRIOR'|'MAGE'|'HEALER'>} [allowedPhenotypes] - Permitted character archetypes.
 * @property {Partial<BaseStats>} [statDeltas] - Net attribute delta applied on equip.
 * @property {function(CharacterSnapshot): string} [effect] - Consumable resolution callback.
 */

/**
 * @typedef {Object} EnemyDefinition
 * @property {string} label - Canonical bestiary display name.
 * @property {string} sprite - ASCII / Unicode iconic fallback glyph.
 * @property {BaseStats} baseStats - Baseline physical attributes.
 * @property {string} [weakness] - Elemental vulnerability identifier.
 * @property {string} [resistance] - Elemental resistance identifier.
 * @property {string} targeting - AI targeting prioritization heuristic.
 * @property {{ exp: number, gold: number, item?: string }} rewards - Spoils granted on defeat.
 * @property {{ id: string, chance: number, duration: number }} [ailmentProc] - On-hit status ailment payload.
 * @property {boolean} [isBoss] - Boss encounter classification flag.
 * @property {number} [phaseTwoThreshold] - Boss phase 2 transition HP ratio.
 * @property {{ sprite?: string, atk: number, def: number, agi: number }} [phaseTwoStats] - Phase 2 enraged stat line.
 * @property {Array<{ type: string, power?: number, label: string, sfx?: string }>} [rotation] - Boss action queue.
 */

/**
 * @typedef {Object} AetherNodeDefinition
 * @property {string} id - Authoritative constellation node key.
 * @property {'IRON'|'EMBER'|'TIDE'|'LUMEN'|'UMBRA'} essence - Dominant elemental branch.
 * @property {string} label - Display title of node.
 * @property {string} desc - Tactical description.
 * @property {'attribute'|'active'|'keystone'} type - Behavioral node archetype.
 * @property {boolean} [isRoot] - Discipline root node indicator.
 * @property {string} [element] - Elemental property of active skills.
 * @property {string} [subType] - Kinetic attack subtype ('strike'|'bolt'|'heal').
 * @property {'enemy'|'ally'} [targetType] - Tactical activation targeting scope.
 * @property {number} [mult] - Physical attack damage multiplier.
 * @property {number} [power] - Absolute spell power score.
 * @property {number} [mpCost] - Mana expenditure required to activate.
 * @property {boolean} [resonance] - Flag asserting harmonic channeling requirement.
 * @property {number} [tier] - Node constellation tier level.
 * @property {Partial<BaseStats>} [statDeltas] - Passive attribute increments.
 * @property {string[]} neighbors - Adjacent topological graph connection IDs.
 * @property {number} spCost - Skill point price to attune node.
 * @property {string|null} capabilityTag - Associated SDCP-001 capability token.
 * @property {'KNOCKBACK'|'PULL'} [displacement] - Tactical grid row displacement action.
 */

/**
 * @typedef {Object} WorldMutationOverride
 * @property {number} x - Target horizontal grid position.
 * @property {number} y - Target vertical grid position.
 * @property {string} tile - Replacement tile legend symbol.
 */

/**
 * @typedef {Object} WorldMutationDefinition
 * @property {string} id - World mutation identifier.
 * @property {string} [flag] - Legacy single flag predicate.
 * @property {number} [targetX] - Legacy target horizontal coordinate.
 * @property {number} [targetY] - Legacy target vertical coordinate.
 * @property {string} [replacementTile] - Legacy replacement glyph.
 * @property {Record<string, boolean>} [requiresFlags] - Mandatory chronicle flags mask.
 * @property {WorldMutationOverride[]} [overrides] - Collection of spatial coordinate transmutations.
 */

/**
 * @typedef {Object} TileDefinition
 * @property {string} id - Internal spatial tile identity token.
 * @property {string} label - Full name of physical terrain.
 * @property {string} char - Standard display character glyph.
 * @property {string} cls - CSS class name for DOM rendering.
 * @property {boolean} walkable - Collision passable assertion flag.
 * @property {string} desc - Sensor inspection telemetry summary.
 */

/**
 * @typedef {Object} QuestStage
 * @property {string} desc - Narrative operational objective.
 * @property {boolean} completed - Stage termination assertion flag.
 */

/**
 * @typedef {Object} QuestDefinition
 * @property {string} id - Unique quest identifier.
 * @property {string} title - Narrative journal title.
 * @property {Record<string|number, QuestStage>} stages - Progressive sequence of narrative milestones.
 * @property {{ gold: number, exp: number, item?: string }} rewards - Completion reward container.
 * @property {string} [requiredFlag] - Prerequisite flag assertion.
 */

/**
 * @typedef {Object} DialogueNode
 * @property {string} id - Step identifier inside conversation graph.
 * @property {string} text - Spoken dialogue text with dynamic interpolation tokens.
 * @property {Array<{ requireFlag?: string, requireQuestStage?: { questId: string, minStage: number }, target: string }>} [redirects] - State predicates.
 * @property {Array<{ text: string, next: string|null, requireItem?: string, lockReason?: string }>} [choices] - Interactive options.
 * @property {string|null} [next] - Unconditional subsequent node target ID.
 * @property {string} [giveItem] - Item granted upon node completion.
 * @property {number} [giveGold] - Gold credited upon node completion.
 * @property {string} [setFlag] - World flag set upon node completion.
 * @property {{ questId: string, stage: number }} [advanceQuest] - Quest progression trigger.
 * @property {string} [takeItem] - Consumable deducted upon node completion.
 * @property {string} [completeQuest] - Quest completion trigger.
 */

/**
 * @typedef {Object} DialogueDefinition
 * @property {string} id - Master conversation key.
 * @property {string} speaker - Display title of interacting NPC.
 * @property {DialogueNode[]} nodes - Directed dialogue state graph.
 */

//#endregion

const EmberlightManifest = (() => {
	const manifest = {
		schemaVersion: '1.2.0',
		protocolVersion: 'VSRP-001',

		//#region [SEC-01] Engine Settings & Operational Tuning Profile
		// --- Centralized Operational Settings Profile (VSRP-001 Config SSOT) ---
		DefaultSettings: {
			version: '1.0.0',
			protocolVersion: 'VSRP-001',
			input: {
				keymap: {
					UP: ['KeyW', 'ArrowUp'],
					DOWN: ['KeyS', 'ArrowDown'],
					LEFT: ['KeyA', 'ArrowLeft'],
					RIGHT: ['KeyD', 'ArrowRight'],
					CONFIRM: ['Enter', 'Space'],
					CANCEL: ['Escape', 'Backspace'],
					TOGGLE_EXPAND_DECK: ['KeyZ'],
					TOGGLE_3D_VIEW: ['KeyX'],
					STRAFE_LEFT: ['KeyQ'],
					MENU_ARMORY: ['KeyE'],
					MENU_PROGRESSION: ['KeyT'],
					MENU_STATUS: ['KeyC'],
					MENU_POUCH: ['KeyI'],
					MENU_SHOP: ['KeyB'],
					MENU_CHRONICLE: ['KeyJ'],
					REST: ['KeyR'],
					FIELD_SCORCH: ['KeyF'],
					FIELD_FREEZE: ['KeyG'],
					FIELD_CONSECRATE: ['KeyH'],
					FIELD_DISPEL: ['KeyV'],
					CHOICE_1: ['Digit1', 'Numpad1'],
					CHOICE_2: ['Digit2', 'Numpad2'],
					CHOICE_3: ['Digit3', 'Numpad3'],
					CHOICE_4: ['Digit4', 'Numpad4'],
				},
			},
			audio: {
				masterVolume: 0.8,
				sfxVolume: 1.0,
				bgmVolume: 0.5,
				isMuted: false,
			},
			tuning: {
				combatEncounterRate: 0.35,
				criticalMultiplier: 1.5,
				stepPoisonTickRate: 4,
			},
			accessibility: {
				screenShake: true,
				highContrastUI: false,
				crtScanlines: true,
			},
			debug: {
				godMode: false,
				showCollisionMesh: false,
				logTelemetry: true,
			},
		},
		//#endregion

		//#region [SEC-02] Session Baseline & Exploration Configuration
		// --- Authoritative Session & Engine Baseline ---
		SessionConfig: {
			startingGold: 100,
			startingInventory: { POTION: 3, ETHER: 1 },
			startingWorldPos: { x: 1, y: 1 },
			townRespawnPos: { x: 1, y: 1 },
			defaultShopId: 'VILLAGE_BLACKSMITH',
		},

		// --- Exploration Engine Configuration ---
		ExplorationConfig: {
			minDangerSteps: 2,
			encounterChance: 0.35,
			defaultEncounterKey: 'DEFAULT',
		},
		//#endregion

		//#region [SEC-03] Party Roster, Phenotypes & Stat Growth Curves
		// --- Progression & Scaling Curves ---
		Curves: {
			/**
			 * Pure curve projection calculating total EXP required to achieve target level.
			 * [Pure Query]
			 * @param {number} level - Numerical target level.
			 * @returns {number} Required EXP threshold.
			 */
			expForNextLevel: (level) => Math.round(20 * level ** 1.4),
		},

		// --- Concrete Party Instances ---
		/** @type {Array<{ instanceId: string, name: string, phenotype: 'HERO'|'WARRIOR'|'MAGE'|'HEALER' }>} */
		PartyRoster: [
			{ instanceId: 'hero', name: 'Aldric', phenotype: 'HERO' },
			{ instanceId: 'warrior', name: 'Brogan', phenotype: 'WARRIOR' },
			{ instanceId: 'mage', name: 'Selene', phenotype: 'MAGE' },
			{ instanceId: 'healer', name: 'Wren', phenotype: 'HEALER' },
		],

		// --- Phenotype Archetypes (Stats, Growths, Displays) ---
		/** @type {Record<string, { label: string, baseStats: BaseStats, growth: BaseStats }>} */
		Phenotypes: {
			HERO: {
				label: 'Hero',
				baseStats: { hp: 32, mp: 12, atk: 9, def: 5, agi: 7 },
				growth: { hp: 6, mp: 2, atk: 2, def: 1, agi: 1 },
			},
			WARRIOR: {
				label: 'Warrior',
				baseStats: { hp: 44, mp: 4, atk: 12, def: 8, agi: 5 },
				growth: { hp: 9, mp: 1, atk: 3, def: 2, agi: 1 },
			},
			MAGE: {
				label: 'Mage',
				baseStats: { hp: 20, mp: 24, atk: 4, def: 2, agi: 8 },
				growth: { hp: 3, mp: 5, atk: 1, def: 1, agi: 2 },
			},
			HEALER: {
				label: 'Healer',
				baseStats: { hp: 24, mp: 20, atk: 5, def: 3, agi: 6 },
				growth: { hp: 4, mp: 4, atk: 1, def: 1, agi: 1 },
			},
		},
		//#endregion

		//#region [SEC-04] Item Catalog, Equipment & Relic Artifacts
		// --- Item & Equipment Catalog ---
		/** @type {Record<string, ItemDefinition>} */
		Items: {
			// Consumables
			POTION: {
				id: 'POTION',
				label: 'Health Potion',
				desc: 'Restores 25 HP',
				cost: 15,
				targetType: 'ally_alive',
				/**
				 * Applies vital restoration delta directly to target character snapshot.
				 * [State Mutating]
				 * @param {CharacterSnapshot} target - Target character object.
				 * @returns {string} Battle log text snippet.
				 */
				effect(target) {
					const curHp = target.hp || 0;
					const maxHp = target.maxHp || 30;
					const healed = Math.min(25, maxHp - curHp);
					target.hp = curHp + healed;
					return `restoring ${healed} HP!`;
				},
			},
			ETHER: {
				id: 'ETHER',
				label: 'Ether Vial',
				desc: 'Restores 15 MP',
				cost: 20,
				targetType: 'ally_alive',
				/**
				 * Applies mana restoration delta directly to target character snapshot.
				 * [State Mutating]
				 * @param {CharacterSnapshot} target - Target character object.
				 * @returns {string} Battle log text snippet.
				 */
				effect(target) {
					const curMp = target.mp || 0;
					const maxMp = target.maxMp || 10;
					const restored = Math.min(15, maxMp - curMp);
					target.mp = curMp + restored;
					return `restoring ${restored} MP!`;
				},
			},
			PHOENIX_EMBER: {
				id: 'PHOENIX_EMBER',
				label: 'Phoenix Ember',
				desc: 'Revives with 50% HP',
				cost: 45,
				targetType: 'ally_dead',
				/**
				 * Revives fallen entity and restores 50% maximum hit points.
				 * [State Mutating]
				 * @param {CharacterSnapshot & { alive?: boolean }} target - Target character object.
				 * @returns {string} Battle log text snippet.
				 */
				effect(target) {
					target.alive = true;
					const maxHp = target.maxHp || 30;
					target.hp = Math.max(1, Math.round(maxHp * 0.5));
					return `reviving them with ${target.hp} HP!`;
				},
			},

			// Weapons
			IRON_SWORD: {
				id: 'IRON_SWORD',
				label: 'Iron Sword',
				desc: '+5 ATK',
				slot: 'weapon',
				requirements: { atk: 6 },
				allowedPhenotypes: ['HERO', 'WARRIOR'],
				statDeltas: { atk: 5 },
				cost: 30,
			},
			OAK_STAFF: {
				id: 'OAK_STAFF',
				label: 'Oak Staff',
				desc: '+2 ATK, +6 MP',
				slot: 'weapon',
				requirements: { mp: 12 },
				allowedPhenotypes: ['MAGE', 'HEALER'],
				statDeltas: { atk: 2, mp: 6 },
				cost: 25,
			},

			// Armor
			CHAIN_VEST: {
				id: 'CHAIN_VEST',
				label: 'Chain Vest',
				desc: '+4 DEF, +8 HP',
				slot: 'armor',
				requirements: { def: 4, hp: 25 },
				allowedPhenotypes: ['HERO', 'WARRIOR'],
				statDeltas: { def: 4, hp: 8 },
				cost: 40,
			},
			CHAINMAIL: {
				id: 'CHAINMAIL',
				label: 'Reinforced Mail',
				desc: '+5 DEF, +12 HP',
				slot: 'armor',
				requirements: { def: 6, hp: 35 },
				allowedPhenotypes: ['HERO', 'WARRIOR'],
				statDeltas: { def: 5, hp: 12 },
				cost: 90,
			},
			MAGE_ROBE: {
				id: 'MAGE_ROBE',
				label: 'Mage Robe',
				desc: '+2 DEF, +10 MP',
				slot: 'armor',
				requirements: { mp: 14 },
				allowedPhenotypes: ['MAGE', 'HEALER'],
				statDeltas: { def: 2, mp: 10 },
				cost: 35,
			},

			// Accessories
			SWIFT_RING: {
				id: 'SWIFT_RING',
				label: 'Swift Ring',
				desc: '+3 AGI',
				slot: 'accessory',
				requirements: { agi: 4 },
				allowedPhenotypes: ['HERO', 'WARRIOR', 'MAGE', 'HEALER'],
				statDeltas: { agi: 3 },
				cost: 50,
			},
			// Legendary Boss Relic
			CINDER_CORE: {
				id: 'CINDER_CORE',
				label: 'Cinder Core',
				desc: '+8 ATK, +6 DEF, +10 Max HP',
				slot: 'accessory',
				requirements: { level: 2 },
				allowedPhenotypes: ['HERO', 'WARRIOR', 'MAGE', 'HEALER'],
				statDeltas: { atk: 8, def: 6, hp: 10 },
				cost: 250,
			},
		},
		//#endregion

		//#region [SEC-05] Bestiary Registry & Tactical Encounter Tables
		// --- Enemy Registry ---
		/** @type {Record<string, EnemyDefinition>} */
		Enemies: {
			SHADE_WOLF: {
				label: 'Shade Wolf',
				sprite: '🐺',
				baseStats: { hp: 18, atk: 6, def: 2, agi: 6 },
				weakness: 'FIRE',
				resistance: 'ICE',
				targeting: 'RANDOM',
				rewards: { exp: 8, gold: 6 },
				ailmentProc: { id: 'POISON', chance: 0.35, duration: 3 },
			},
			BONE_ARCHER: {
				label: 'Bone Archer',
				sprite: '🏹',
				baseStats: { hp: 14, atk: 8, def: 1, agi: 9 },
				weakness: 'HOLY',
				resistance: 'PHYSICAL',
				targeting: 'LOWEST_DEF',
				rewards: { exp: 11, gold: 9 },
			},
			IRON_BRUTE: {
				label: 'Iron Brute',
				sprite: '👹',
				baseStats: { hp: 30, atk: 10, def: 6, agi: 3 },
				weakness: 'LIGHTNING',
				resistance: 'PHYSICAL',
				targeting: 'HIGHEST_ATK',
				rewards: { exp: 16, gold: 14 },
			},
			CRYPT_SKELETON: {
				label: 'Crypt Skeleton',
				sprite: '💀',
				baseStats: { hp: 28, atk: 9, def: 8, agi: 4 },
				weakness: 'HOLY',
				resistance: 'PHYSICAL',
				targeting: 'HIGHEST_ATK',
				rewards: { exp: 24, gold: 18 },
			},
			BLIGHT_SPIDER: {
				label: 'Blight Spider',
				sprite: '🕷',
				baseStats: { hp: 16, atk: 8, def: 2, agi: 9 },
				weakness: 'FIRE',
				resistance: 'HOLY',
				targeting: 'LOWEST_DEF',
				rewards: { exp: 20, gold: 12 },
				ailmentProc: { id: 'POISON', chance: 0.5, duration: 3 },
			},
			DREAD_ACOLYTE: {
				label: 'Dread Acolyte',
				sprite: '🧙‍♂️',
				baseStats: { hp: 22, atk: 11, def: 4, agi: 6 },
				weakness: 'HOLY',
				resistance: 'FIRE',
				targeting: 'RANDOM',
				rewards: { exp: 32, gold: 28 },
				ailmentProc: { id: 'BURN', chance: 0.4, duration: 3 },
			},
			// --- BOSS: Malakor, The Cinder Revenant ---
			CINDER_REVENANT: {
				label: 'Malakor, Cinder Revenant',
				sprite: '🔥💀',
				isBoss: true,
				baseStats: { hp: 160, atk: 15, def: 10, agi: 5 },
				weakness: 'ICE',
				resistance: 'FIRE',
				phaseTwoThreshold: 0.5,
				phaseTwoStats: { sprite: '🌋', atk: 19, def: 5, agi: 9 },
				targeting: 'ROTATION',
				rewards: { exp: 150, gold: 200, item: 'CINDER_CORE' },
				rotation: [
					{
						type: 'CLEAVE_TWO',
						power: 1.3,
						label: 'Hellfire Cleave',
						sfx: 'ATTACK_HIT',
					},
					{ type: 'STUN_LOWEST', label: 'Ashen Choke', sfx: 'SPELL_BOLT' },
					{
						type: 'AOE_ALL',
						power: 1.1,
						label: 'Cataclysm Supernova',
						sfx: 'SPELL_BOLT',
					},
				],
				ailmentProc: { id: 'BURN', chance: 0.45, duration: 3 },
			},
		},

		// --- Encounter Tables ---
		/** @type {Record<string, string[]>} */
		Encounters: {
			DEFAULT: ['SHADE_WOLF', 'BONE_ARCHER', 'IRON_BRUTE'],
			WOLF_PACK: ['SHADE_WOLF', 'SHADE_WOLF'],
			CRYPT_SANCTUM: ['DREAD_ACOLYTE', 'CRYPT_SKELETON'],
			SPIDER_NEST: ['BLIGHT_SPIDER', 'BLIGHT_SPIDER'],
			CATACOMBS_DEEP: ['CRYPT_SKELETON', 'BLIGHT_SPIDER', 'DREAD_ACOLYTE'],
			BOSS_MALAKOR: ['CINDER_REVENANT'],
		},
		//#endregion

		//#region [SEC-06] Aether Matrix Constellation & Essence Graph
		// --- Aether Matrix Constellation Graph (PRS-ARC-020) ---
		/** @type {Record<string, { id: string, label: string, element: string, role: string }>} */
		AetherEssences: {
			IRON: {
				id: 'IRON',
				label: 'Path of Iron',
				element: 'PHYSICAL',
				role: 'Vanguard / Bulwark',
			},
			EMBER: {
				id: 'EMBER',
				label: 'Path of Ember',
				element: 'FIRE',
				role: 'Combustion / Strike',
			},
			TIDE: {
				id: 'TIDE',
				label: 'Path of Tide',
				element: 'ICE',
				role: 'Time / Crystallization',
			},
			LUMEN: {
				id: 'LUMEN',
				label: 'Path of Lumen',
				element: 'HOLY',
				role: 'Restoration / Wards',
			},
			UMBRA: {
				id: 'UMBRA',
				label: 'Path of Umbra',
				element: 'POISON',
				role: 'Affliction / Skirmish',
			},
		},

		/** @type {Record<string, AetherNodeDefinition>} */
		AetherNodes: {
			// === IRON ESSENCE NODES ===
			iron_root: {
				id: 'iron_root',
				essence: 'IRON',
				label: 'Bulwark Discipline',
				desc: '+8 Max HP, +2 DEF',
				type: 'attribute',
				isRoot: true,
				statDeltas: { hp: 8, def: 2 },
				neighbors: ['iron_cleave', 'iron_guard_1', 'iron_hp_1'],
				spCost: 1,
				capabilityTag: null,
			},
			iron_cleave: {
				id: 'iron_cleave',
				essence: 'IRON',
				label: 'Heavy Cleave',
				desc: 'Brutal frontline strike (1.4x ATK)',
				type: 'active',
				element: 'PHYSICAL',
				subType: 'strike',
				targetType: 'enemy',
				mult: 1.4,
				mpCost: 0,
				neighbors: ['iron_root', 'iron_sunder', 'ember_bridge_1'],
				spCost: 1,
				capabilityTag: null,
			},
			iron_guard_1: {
				id: 'iron_guard_1',
				essence: 'IRON',
				label: 'Vanguard Aegis',
				desc: 'Frontline body-blocks single-target strikes aimed at backline',
				type: 'keystone',
				statDeltas: { def: 2 },
				neighbors: ['iron_root', 'lumen_bridge_1', 'iron_def_1'],
				spCost: 2,
				capabilityTag: null,
			},
			iron_hp_1: {
				id: 'iron_hp_1',
				essence: 'IRON',
				label: 'Iron Flesh',
				desc: '+12 Max HP',
				type: 'attribute',
				statDeltas: { hp: 12 },
				neighbors: ['iron_root', 'iron_def_1'],
				spCost: 1,
				capabilityTag: null,
			},
			iron_def_1: {
				id: 'iron_def_1',
				essence: 'IRON',
				label: 'Fortified Posture',
				desc: '+3 DEF, +4 Max HP',
				type: 'attribute',
				statDeltas: { def: 3, hp: 4 },
				neighbors: ['iron_guard_1', 'iron_hp_1', 'iron_sunder'],
				spCost: 1,
				capabilityTag: null,
			},
			iron_sunder: {
				id: 'iron_sunder',
				essence: 'IRON',
				label: 'Armor Sunder',
				desc: 'Crushing blow that pierces defense (1.7x ATK)',
				type: 'active',
				element: 'PHYSICAL',
				subType: 'strike',
				targetType: 'enemy',
				mult: 1.7,
				mpCost: 1,
				neighbors: ['iron_cleave', 'iron_def_1', 'iron_bru_3'],
				spCost: 2,
				capabilityTag: null,
			},
			iron_bru_3: {
				id: 'iron_bru_3',
				essence: 'IRON',
				label: 'Juggernaut Impact',
				desc: 'Cataclysmic melee execution (2.2x ATK)',
				type: 'active',
				element: 'PHYSICAL',
				subType: 'strike',
				targetType: 'enemy',
				mult: 2.2,
				mpCost: 3,
				resonance: true,
				tier: 3,
				neighbors: ['iron_sunder'],
				spCost: 3,
				capabilityTag: null,
			},

			// === EMBER ESSENCE NODES ===
			ember_root: {
				id: 'ember_root',
				essence: 'EMBER',
				label: 'Spark Attunement',
				desc: '+3 ATK, +6 Max MP',
				type: 'attribute',
				isRoot: true,
				statDeltas: { atk: 3, mp: 6 },
				neighbors: ['ember_bolt_1', 'ember_burn_1', 'ember_crit_1'],
				spCost: 1,
				capabilityTag: 'cap:elemental.scorch',
			},
			ember_bolt_1: {
				id: 'ember_bolt_1',
				essence: 'EMBER',
				label: 'Flame Spark',
				desc: 'Direct fire projectile (Power 10)',
				type: 'active',
				element: 'FIRE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 10,
				mpCost: 3,
				neighbors: ['ember_root', 'ember_bridge_1', 'ember_burst'],
				spCost: 1,
				capabilityTag: 'cap:elemental.scorch',
			},
			ember_burn_1: {
				id: 'ember_burn_1',
				essence: 'EMBER',
				label: 'Thermal Surge',
				desc: '+2 ATK, +1 AGI',
				type: 'attribute',
				statDeltas: { atk: 2, agi: 1 },
				neighbors: ['ember_root', 'ember_catalyst'],
				spCost: 1,
				capabilityTag: null,
			},
			ember_crit_1: {
				id: 'ember_crit_1',
				essence: 'EMBER',
				label: 'Incendiary Focus',
				desc: '+6 Max MP, +2 ATK',
				type: 'attribute',
				statDeltas: { mp: 6, atk: 2 },
				neighbors: ['ember_root', 'ember_burst'],
				spCost: 1,
				capabilityTag: null,
			},
			ember_burst: {
				id: 'ember_burst',
				essence: 'EMBER',
				label: 'Inferno Orb',
				desc: 'High-heat thermal blast (Power 18)',
				type: 'active',
				element: 'FIRE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 18,
				mpCost: 6,
				resonance: true,
				neighbors: ['ember_bolt_1', 'ember_crit_1', 'ember_des_3'],
				spCost: 2,
				capabilityTag: 'cap:elemental.scorch',
			},
			ember_catalyst: {
				id: 'ember_catalyst',
				essence: 'EMBER',
				label: 'Thermal Catalyst',
				desc: 'Fire strikes against frozen or burning targets gain +50% DMG',
				type: 'keystone',
				statDeltas: { atk: 3 },
				neighbors: ['ember_burn_1', 'tide_bridge_1'],
				spCost: 2,
				capabilityTag: 'cap:elemental.scorch',
			},
			ember_des_3: {
				id: 'ember_des_3',
				essence: 'EMBER',
				label: 'Hellfire Conflagration',
				desc: 'Signature pyroclastic devastation (Power 26)',
				type: 'active',
				element: 'FIRE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 26,
				mpCost: 10,
				resonance: true,
				tier: 3,
				neighbors: ['ember_burst'],
				spCost: 3,
				capabilityTag: 'cap:elemental.scorch',
			},

			// === TIDE ESSENCE NODES ===
			tide_root: {
				id: 'tide_root',
				essence: 'TIDE',
				label: 'Flow Attunement',
				desc: '+2 AGI, +8 Max MP',
				type: 'attribute',
				isRoot: true,
				statDeltas: { agi: 2, mp: 8 },
				neighbors: ['tide_frost_1', 'tide_haste_1', 'tide_def_1'],
				spCost: 1,
				capabilityTag: 'cap:elemental.freeze',
			},
			tide_frost_1: {
				id: 'tide_frost_1',
				essence: 'TIDE',
				label: 'Frost Spike',
				desc: 'Piercing ice crystallization (Power 12)',
				type: 'active',
				element: 'ICE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 12,
				mpCost: 4,
				neighbors: ['tide_root', 'tide_bridge_1', 'tide_blizzard'],
				spCost: 1,
				capabilityTag: 'cap:elemental.freeze',
			},
			tide_haste_1: {
				id: 'tide_haste_1',
				essence: 'TIDE',
				label: 'Quickstep Surge',
				desc: '+2 AGI, +6 Max HP',
				type: 'attribute',
				statDeltas: { agi: 2, hp: 6 },
				neighbors: ['tide_root', 'tide_chronos'],
				spCost: 1,
				capabilityTag: null,
			},
			tide_def_1: {
				id: 'tide_def_1',
				essence: 'TIDE',
				label: 'Glacial Shell',
				desc: '+2 DEF, +6 Max MP',
				type: 'attribute',
				statDeltas: { def: 2, mp: 6 },
				neighbors: ['tide_root', 'umbra_bridge_1'],
				spCost: 1,
				capabilityTag: null,
			},
			tide_blizzard: {
				id: 'tide_blizzard',
				essence: 'TIDE',
				label: 'Glacial Nova',
				desc: 'Sub-zero freezing blast (Power 20)',
				type: 'active',
				element: 'ICE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 20,
				mpCost: 7,
				resonance: true,
				neighbors: ['tide_frost_1', 'tide_freeze_3'],
				spCost: 2,
				capabilityTag: 'cap:elemental.freeze',
			},
			tide_chronos: {
				id: 'tide_chronos',
				essence: 'TIDE',
				label: 'Temporal Velocity',
				desc: 'Reduces action CTB delay by 15% and grants +2 AGI',
				type: 'keystone',
				statDeltas: { agi: 2 },
				neighbors: ['tide_haste_1'],
				spCost: 2,
				capabilityTag: null,
			},
			tide_freeze_3: {
				id: 'tide_freeze_3',
				essence: 'TIDE',
				label: 'Absolute Zero',
				desc: 'Complete thermal cessation blast (Power 28)',
				type: 'active',
				element: 'ICE',
				subType: 'bolt',
				targetType: 'enemy',
				power: 28,
				mpCost: 12,
				resonance: true,
				tier: 3,
				neighbors: ['tide_blizzard'],
				spCost: 3,
				capabilityTag: 'cap:elemental.freeze',
			},

			// === LUMEN ESSENCE NODES ===
			lumen_root: {
				id: 'lumen_root',
				essence: 'LUMEN',
				label: 'Radiant Dawn',
				desc: '+8 Max HP, +8 Max MP',
				type: 'attribute',
				isRoot: true,
				statDeltas: { hp: 8, mp: 8 },
				neighbors: ['lumen_heal_1', 'lumen_smite_1', 'lumen_ward_1'],
				spCost: 1,
				capabilityTag: 'cap:sanctuary.consecrate',
			},
			lumen_heal_1: {
				id: 'lumen_heal_1',
				essence: 'LUMEN',
				label: 'Purifying Light',
				desc: 'Holy recovery incantation (Power 14)',
				type: 'active',
				element: 'HOLY',
				subType: 'heal',
				targetType: 'ally',
				power: 14,
				mpCost: 3,
				neighbors: ['lumen_root', 'lumen_bridge_1', 'lumen_sanctuary'],
				spCost: 1,
				capabilityTag: 'cap:sanctuary.consecrate',
			},
			lumen_smite_1: {
				id: 'lumen_smite_1',
				essence: 'LUMEN',
				label: 'Holy Smite',
				desc: 'Radiant smiting beam (Power 12)',
				type: 'active',
				element: 'HOLY',
				subType: 'bolt',
				targetType: 'enemy',
				power: 12,
				mpCost: 4,
				neighbors: ['lumen_root', 'lumen_judg_3'],
				spCost: 1,
				capabilityTag: null,
			},
			lumen_ward_1: {
				id: 'lumen_ward_1',
				essence: 'LUMEN',
				label: 'Aegis Ward',
				desc: '+2 DEF, +1 ATK',
				type: 'attribute',
				statDeltas: { def: 2, atk: 1 },
				neighbors: ['lumen_root', 'lumen_res_3'],
				spCost: 1,
				capabilityTag: null,
			},
			lumen_sanctuary: {
				id: 'lumen_sanctuary',
				essence: 'LUMEN',
				label: 'Greater Sanctuary',
				desc: 'Mass radiant restoration (Power 24)',
				type: 'active',
				element: 'HOLY',
				subType: 'heal',
				targetType: 'ally',
				power: 24,
				mpCost: 7,
				resonance: true,
				neighbors: ['lumen_heal_1', 'lumen_res_3'],
				spCost: 2,
				capabilityTag: 'cap:sanctuary.consecrate',
			},
			lumen_res_3: {
				id: 'lumen_res_3',
				essence: 'LUMEN',
				label: 'Divine Grace',
				desc: 'Healing potency +25% and purges poison/burn on target',
				type: 'keystone',
				statDeltas: { def: 2, mp: 6 },
				neighbors: ['lumen_ward_1', 'lumen_sanctuary'],
				spCost: 2,
				capabilityTag: 'cap:sanctuary.consecrate',
			},
			lumen_judg_3: {
				id: 'lumen_judg_3',
				essence: 'LUMEN',
				label: 'Pillar of Judgment',
				desc: 'Heavenly smiting blast (Power 28)',
				type: 'active',
				element: 'HOLY',
				subType: 'bolt',
				targetType: 'enemy',
				power: 28,
				mpCost: 12,
				resonance: true,
				tier: 3,
				neighbors: ['lumen_smite_1'],
				spCost: 3,
				capabilityTag: null,
			},

			// === UMBRA ESSENCE NODES ===
			umbra_root: {
				id: 'umbra_root',
				essence: 'UMBRA',
				label: 'Shadow Discipline',
				desc: '+2 ATK, +2 AGI, +4 Max MP',
				type: 'attribute',
				isRoot: true,
				statDeltas: { atk: 2, agi: 2, mp: 4 },
				neighbors: ['umbra_strike_1', 'umbra_toxin_1', 'umbra_gale_1'],
				spCost: 1,
				capabilityTag: 'cap:elemental.dispel',
			},
			umbra_strike_1: {
				id: 'umbra_strike_1',
				essence: 'UMBRA',
				label: 'Shadow Pierce',
				desc: 'Precision skirmish strike (1.5x ATK)',
				type: 'active',
				element: 'PHYSICAL',
				subType: 'strike',
				targetType: 'enemy',
				mult: 1.5,
				mpCost: 1,
				neighbors: ['umbra_root', 'umbra_bridge_1', 'umbra_assassinate'],
				spCost: 1,
				capabilityTag: null,
			},
			umbra_toxin_1: {
				id: 'umbra_toxin_1',
				essence: 'UMBRA',
				label: 'Blight Touch',
				desc: '+2 ATK, +6 Max MP',
				type: 'attribute',
				statDeltas: { atk: 2, mp: 6 },
				neighbors: ['umbra_root', 'umbra_dispel'],
				spCost: 1,
				capabilityTag: null,
			},
			umbra_gale_1: {
				id: 'umbra_gale_1',
				essence: 'UMBRA',
				label: 'Wind Cloak',
				desc: '+2 AGI, +2 DEF',
				type: 'attribute',
				statDeltas: { agi: 2, def: 2 },
				neighbors: ['umbra_root', 'umbra_dispel'],
				spCost: 1,
				capabilityTag: 'cap:elemental.dispel',
			},
			umbra_dispel: {
				id: 'umbra_dispel',
				essence: 'UMBRA',
				label: 'Shadow Gale',
				desc: 'Dispersing miasma gust (Power 14)',
				type: 'active',
				element: 'POISON',
				subType: 'bolt',
				targetType: 'enemy',
				power: 14,
				mpCost: 4,
				neighbors: ['umbra_toxin_1', 'umbra_gale_1', 'umbra_assassinate'],
				spCost: 2,
				capabilityTag: 'cap:elemental.dispel',
			},
			umbra_assassinate: {
				id: 'umbra_assassinate',
				essence: 'UMBRA',
				label: 'Death Mark',
				desc: 'Lethal shadow assassination (2.4x ATK)',
				type: 'active',
				element: 'PHYSICAL',
				subType: 'strike',
				targetType: 'enemy',
				mult: 2.4,
				mpCost: 4,
				resonance: true,
				tier: 3,
				neighbors: ['umbra_strike_1', 'umbra_dispel'],
				spCost: 3,
				capabilityTag: null,
			},

			// === CROSS-DISCIPLINE BRIDGES (HYBRIDS) ===
			ember_bridge_1: {
				id: 'ember_bridge_1',
				essence: 'EMBER',
				label: 'Molten Edge',
				desc: 'Ignited physical blade strike (1.8x ATK)',
				type: 'active',
				element: 'FIRE',
				subType: 'strike',
				targetType: 'enemy',
				mult: 1.8,
				mpCost: 3,
				neighbors: ['iron_cleave', 'ember_bolt_1'],
				spCost: 2,
				capabilityTag: 'cap:elemental.scorch',
			},
			lumen_bridge_1: {
				id: 'lumen_bridge_1',
				essence: 'LUMEN',
				label: 'Vanguard Beacon',
				desc: 'Protective healing surge (Power 12)',
				type: 'active',
				element: 'HOLY',
				subType: 'heal',
				targetType: 'ally',
				power: 12,
				mpCost: 4,
				neighbors: ['iron_guard_1', 'lumen_heal_1'],
				spCost: 2,
				capabilityTag: 'cap:sanctuary.consecrate',
			},
			tide_bridge_1: {
				id: 'tide_bridge_1',
				essence: 'TIDE',
				label: 'Thermal Shock Catalyst',
				desc: 'Combines Ice and Fire disciplines for +35% elemental reaction DMG',
				type: 'keystone',
				statDeltas: { atk: 2, agi: 1 },
				neighbors: ['ember_catalyst', 'tide_frost_1'],
				spCost: 2,
				capabilityTag: 'cap:elemental.freeze',
			},
			umbra_bridge_1: {
				id: 'umbra_bridge_1',
				essence: 'UMBRA',
				label: 'Mist Walker',
				desc: 'Evasion +15% and complete immunity to toxic miasma',
				type: 'keystone',
				statDeltas: { agi: 2, def: 1 },
				neighbors: ['tide_def_1', 'umbra_strike_1'],
				spCost: 2,
				capabilityTag: 'cap:elemental.dispel',
			},
		},
		//#endregion

		//#region [SEC-07] Archetype Progression Skill Trees
		// --- Progression Skill Trees ---
		SkillTrees: {
			HERO: {
				RESOLVE: [
					{
						id: 'hero_res_1',
						tier: 1,
						label: 'Iron Will',
						desc: '+4 Max HP',
						type: 'passive',
						statDeltas: { hp: 4 },
					},
					{
						id: 'hero_res_2',
						tier: 2,
						label: 'Steadfast',
						desc: '+2 DEF',
						type: 'passive',
						statDeltas: { def: 2 },
					},
					{
						id: 'hero_res_3',
						tier: 3,
						label: 'Unbroken',
						desc: '+2 AGI',
						type: 'passive',
						statDeltas: { agi: 2 },
					},
				],
				BLADE_ARTS: [
					{
						id: 'hero_bla_1',
						tier: 1,
						label: 'Power Strike',
						desc: 'Heavy strike',
						type: 'active',
						element: 'PHYSICAL',
						targetType: 'enemy',
						mpCost: 0,
						mult: 1.3,
						subType: 'strike',
					},
					{
						id: 'hero_bla_2',
						tier: 2,
						label: 'Piercing Drag',
						desc: 'Pull backline foe into vanguard',
						type: 'active',
						element: 'PHYSICAL',
						targetType: 'enemy',
						mpCost: 3,
						mult: 1.6,
						displacement: 'PULL',
						subType: 'strike',
					},
					{
						id: 'hero_bla_3',
						tier: 3,
						label: 'Ember Finisher',
						desc: 'Signature hit',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 2,
						mult: 2.1,
						subType: 'strike',
						resonance: true,
					},
				],
				LIGHT_FRAGMENTS: [
					{
						id: 'hero_lig_1',
						tier: 1,
						label: 'Minor Light',
						desc: 'Small heal',
						type: 'active',
						element: 'HOLY',
						targetType: 'ally',
						mpCost: 2,
						power: 6,
						subType: 'heal',
						resonance: true,
					},
					{
						id: 'hero_lig_2',
						tier: 2,
						label: 'Warding Glow',
						desc: '+1 DEF',
						type: 'passive',
						statDeltas: { def: 1 },
						resonance: true,
					},
					{
						id: 'hero_lig_3',
						tier: 3,
						label: 'Ember Beam',
						desc: 'Magic damage',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 4,
						power: 14,
						subType: 'bolt',
						resonance: true,
					},
				],
			},
			WARRIOR: {
				TACTICAL_DEFENSE: [
					{
						id: 'war_tac_1',
						tier: 1,
						label: 'Bulwark',
						desc: '+6 Max HP',
						type: 'passive',
						statDeltas: { hp: 6 },
					},
					{
						id: 'war_tac_2',
						tier: 2,
						label: 'Guard Stance',
						desc: '+3 DEF',
						type: 'passive',
						statDeltas: { def: 3 },
					},
					{
						id: 'war_tac_3',
						tier: 3,
						label: 'Battle Instinct',
						desc: '+1 AGI',
						type: 'passive',
						statDeltas: { agi: 1 },
					},
				],
				WAR_CRY: [
					{
						id: 'war_cry_1',
						tier: 1,
						label: 'Challenge',
						desc: '+2 ATK',
						type: 'passive',
						statDeltas: { atk: 2 },
					},
					{
						id: 'war_cry_2',
						tier: 2,
						label: 'Rallying Roar',
						desc: '+4 Max HP',
						type: 'passive',
						statDeltas: { hp: 4 },
					},
					{
						id: 'war_cry_3',
						tier: 3,
						label: 'Unyielding',
						desc: '+2 DEF',
						type: 'passive',
						statDeltas: { def: 2 },
					},
				],
				BRUTAL_FORCE: [
					{
						id: 'war_bru_1',
						tier: 1,
						label: 'Heavy Cleave',
						desc: 'Brutal swing',
						type: 'active',
						element: 'PHYSICAL',
						targetType: 'enemy',
						mpCost: 0,
						mult: 1.4,
						subType: 'strike',
					},
					{
						id: 'war_bru_2',
						tier: 2,
						label: 'Shield Slam',
						desc: 'Knock frontline foe into rear',
						type: 'active',
						element: 'PHYSICAL',
						targetType: 'enemy',
						mpCost: 2,
						mult: 1.5,
						displacement: 'KNOCKBACK',
						subType: 'strike',
					},
					{
						id: 'war_bru_3',
						tier: 3,
						label: 'Ember Sunder',
						desc: 'Devastating hit',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 3,
						mult: 2.3,
						subType: 'strike',
						resonance: true,
					},
				],
			},
			MAGE: {
				DESTRUCTION: [
					{
						id: 'mag_des_1',
						tier: 1,
						label: 'Ember Bolt',
						desc: 'Fire bolt',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 4,
						power: 10,
						subType: 'bolt',
					},
					{
						id: 'mag_des_2',
						tier: 2,
						label: 'Flame Lance',
						desc: 'Fire lance',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 8,
						power: 16,
						subType: 'bolt',
					},
					{
						id: 'mag_des_3',
						tier: 3,
						label: 'Meteor Shard',
						desc: 'Heavy meteor',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 14,
						power: 24,
						subType: 'bolt',
					},
				],
				ARCANE_FOCUS: [
					{
						id: 'mag_arc_1',
						tier: 1,
						label: 'Channeling',
						desc: '+6 Max MP',
						type: 'passive',
						statDeltas: { mp: 6 },
					},
					{
						id: 'mag_arc_2',
						tier: 2,
						label: 'Arcane Sight',
						desc: '+2 AGI',
						type: 'passive',
						statDeltas: { agi: 2 },
					},
					{
						id: 'mag_arc_3',
						tier: 3,
						label: 'Leyline Mastery',
						desc: '+10 Max MP',
						type: 'passive',
						statDeltas: { mp: 10 },
					},
				],
				ELEMENTALISM: [
					{
						id: 'mag_ele_1',
						tier: 1,
						label: 'Flame Spark',
						desc: 'Fire spell',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 3,
						power: 10,
						subType: 'bolt',
					},
					{
						id: 'mag_ele_2',
						tier: 2,
						label: 'Frost Spike',
						desc: 'Ice spell',
						type: 'active',
						element: 'ICE',
						targetType: 'enemy',
						mpCost: 5,
						power: 16,
						subType: 'bolt',
					},
					{
						id: 'mag_ele_3',
						tier: 3,
						label: 'Inferno Orb',
						desc: 'High damage',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 8,
						power: 24,
						subType: 'bolt',
						resonance: true,
					},
				],
				PRIMAL_SURGE: [
					{
						id: 'mag_pri_1',
						tier: 1,
						label: 'Static Charge',
						desc: '+1 ATK',
						type: 'passive',
						statDeltas: { atk: 1 },
					},
					{
						id: 'mag_pri_2',
						tier: 2,
						label: 'Mana Shield',
						desc: '+2 DEF',
						type: 'passive',
						statDeltas: { def: 2 },
					},
					{
						id: 'mag_pri_3',
						tier: 3,
						label: 'Ember Nova',
						desc: 'Cataclysm burst',
						type: 'active',
						element: 'FIRE',
						targetType: 'enemy',
						mpCost: 12,
						power: 32,
						subType: 'bolt',
						resonance: true,
					},
				],
			},
			HEALER: {
				RESTORATION: [
					{
						id: 'hea_res_1',
						tier: 1,
						label: 'Minor Heal',
						desc: 'Restores HP',
						type: 'active',
						element: 'HOLY',
						targetType: 'ally',
						mpCost: 3,
						power: 10,
						subType: 'heal',
					},
					{
						id: 'hea_res_2',
						tier: 2,
						label: 'Greater Heal',
						desc: 'Large heal',
						type: 'active',
						element: 'HOLY',
						targetType: 'ally',
						mpCost: 6,
						power: 20,
						subType: 'heal',
					},
					{
						id: 'hea_res_3',
						tier: 3,
						label: 'Divine Grace',
						desc: 'Massive heal',
						type: 'active',
						element: 'HOLY',
						targetType: 'ally',
						mpCost: 10,
						power: 35,
						subType: 'heal',
						resonance: true,
					},
				],
				SANCTUARY: [
					{
						id: 'hea_san_1',
						tier: 1,
						label: 'Blessed Vigor',
						desc: '+4 Max HP',
						type: 'passive',
						statDeltas: { hp: 4 },
					},
					{
						id: 'hea_san_2',
						tier: 2,
						label: 'Serenity',
						desc: '+3 Max MP',
						type: 'passive',
						statDeltas: { mp: 3 },
					},
					{
						id: 'hea_san_3',
						tier: 3,
						label: 'Aegis',
						desc: '+2 DEF',
						type: 'passive',
						statDeltas: { def: 2 },
					},
				],
				SMITING: [
					{
						id: 'hea_smi_1',
						tier: 1,
						label: 'Smite',
						desc: 'Holy strike',
						type: 'active',
						element: 'HOLY',
						targetType: 'enemy',
						mpCost: 4,
						power: 8,
						subType: 'bolt',
						resonance: true,
					},
					{
						id: 'hea_smi_2',
						tier: 2,
						label: 'Righteous Fervor',
						desc: '+1 ATK',
						type: 'passive',
						statDeltas: { atk: 1 },
						resonance: true,
					},
					{
						id: 'hea_smi_3',
						tier: 3,
						label: 'Judgment',
						desc: 'Light blast',
						type: 'active',
						element: 'HOLY',
						targetType: 'enemy',
						mpCost: 10,
						power: 18,
						subType: 'bolt',
						resonance: true,
					},
				],
			},
		},
		//#endregion

		//#region [SEC-08] Spatial Tile Legend & World Topology Maps
		// --- Exploration Matrices & Tile Legend ---
		/** @type {Record<string, TileDefinition>} */
		TileLegend: {
			'#': {
				id: 'WALL',
				label: 'Mountain Peak',
				char: '■',
				cls: 'wall',
				walkable: false,
				desc: 'Impassable jagged rock.',
			},
			'.': {
				id: 'PATH',
				label: 'Cobblestone',
				char: '·',
				cls: 'path',
				walkable: true,
				desc: 'Safe paved road.',
			},
			'"': {
				id: 'GRASS',
				label: 'Tall Grass / Mist',
				char: '░',
				cls: 'grass',
				walkable: true,
				desc: 'Wild biome with danger encounter rolls.',
			},
			'%': {
				id: 'MIRE_MIASMA',
				label: 'Toxic Miasma',
				char: '※',
				cls: 'miasma',
				walkable: true,
				desc: 'Noxious bog vapor. Poisons travelers unless dispelled.',
			},
			'~': {
				id: 'WATER',
				label: 'Abyssal Waterway',
				char: '≈',
				cls: 'water',
				walkable: false,
				desc: 'Deep water chasm. Impassable unless frozen.',
			},
			'=': {
				id: 'ICE',
				label: 'Frozen Bridge',
				char: '≡',
				cls: 'ice',
				walkable: true,
				desc: 'Crystallized ice sheet. Safe to cross.',
			},
			_: {
				id: 'PRESSURE_PLATE',
				label: 'Stone Pressure Plate',
				char: '⏚',
				cls: 'plate',
				walkable: true,
				desc: 'Depressible switch connected to catacomb gates.',
			},
			P: {
				id: 'PORTCULLIS_LOCKED',
				label: 'Iron Portcullis',
				char: '⚏',
				cls: 'portcullis-locked',
				walkable: false,
				desc: 'Heavy iron gate. Blocks passage.',
			},
			'/': {
				id: 'PORTCULLIS_OPEN',
				label: 'Raised Portcullis',
				char: '☵',
				cls: 'portcullis-open',
				walkable: true,
				desc: 'Retracted iron gate. Safe to pass.',
			},
			'@': {
				id: 'CARAVAN',
				label: 'Wandering Caravan',
				char: '🐪',
				cls: 'caravan',
				walkable: false,
				desc: 'Nomadic merchant carrying exotic wares.',
			},
			G: {
				id: 'GUARD',
				label: 'Gate Captain Kael',
				char: '🛡',
				cls: 'npc',
				walkable: false,
				desc: 'Town Guard Commander.',
			},
			V: {
				id: 'VILLAGER',
				label: 'Afflicted Scout',
				char: '👤',
				cls: 'npc',
				walkable: false,
				desc: 'Suffering from catacomb blight.',
			},
			B: {
				id: 'SMITHY',
				label: 'Blacksmith Forge',
				char: '⚒',
				cls: 'town',
				walkable: false,
				desc: "Torvald's Armory & Weapon Forge.",
			},
			F: {
				id: 'FORGE',
				label: 'Relic Crucible',
				char: '⚙',
				cls: 'town',
				walkable: false,
				desc: 'Synthesize resonant equipment.',
			},
			O: {
				id: 'GATE',
				label: 'Town Gate',
				char: '🚪',
				cls: 'path',
				walkable: true,
				desc: 'Outpost exit to the wilderness road.',
			},
			T: {
				id: 'TOWN',
				label: 'Oakhaven Town',
				char: '🏰',
				cls: 'town',
				walkable: true,
				desc: 'Safe settlement with merchant shops.',
			},
			C: {
				id: 'CAMP',
				label: 'Rest Camp',
				char: '▲',
				cls: 'camp',
				walkable: true,
				desc: 'Campsite for full HP/MP recovery.',
			},
			E: {
				id: 'ELDER',
				label: 'Village Elder',
				char: '🧓',
				cls: 'npc',
				walkable: false,
				desc: 'Elder Rowan ready for dialogue.',
			},
			$: {
				id: 'CHEST',
				label: 'Treasure Chest',
				char: '📦',
				cls: 'chest',
				walkable: true,
				desc: 'Ancient lockbox containing relics and gold.',
			},
			'>': {
				id: 'CRYPT',
				label: 'Crypt Descent',
				char: '⛩️',
				cls: 'crypt',
				walkable: true,
				desc: 'Descent into the underground crypt dungeon.',
			},
			'<': {
				id: 'SURFACE',
				label: 'Ascent Ladder',
				char: '🪜',
				cls: 'town',
				walkable: true,
				desc: 'Stairs back up to the surface world.',
			},
		},

		/** @type {string[][]} */
		OverworldMap: [
			[
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'T',
				'E',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'~',
				'~',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'=',
				'=',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'C',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'~',
				'~',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'"',
				'"',
				'"',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'"',
				'#',
				'"',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'"',
				'"',
				'"',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
			],
			[
				'#',
				'"',
				'"',
				'"',
				'#',
				'.',
				'.',
				'"',
				'"',
				'$',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'~',
				'~',
				'.',
				'#',
				'"',
				'%',
				'%',
				'"',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
			],
			[
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'"',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'~',
				'~',
				'.',
				'#',
				'"',
				'%',
				'%',
				'"',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'"',
				'"',
				'#',
				'.',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'"',
				'"',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'"',
				'>',
				'#',
				'.',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'C',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'=',
				'=',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'~',
				'~',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'~',
				'~',
				'~',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'~',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'~',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'~',
				'~',
				'~',
				'~',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'"',
				'"',
				'"',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'~',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'C',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'"',
				'%',
				'%',
				'"',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'~',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'"',
				'%',
				'%',
				'"',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
			],
			[
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'"',
				'"',
				'"',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'P',
				'#',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'C',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'_',
				'.',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'$',
				'#',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'.',
				'~',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'.',
				'#',
				'#',
				'.',
				'.',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'~',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'.',
				'.',
				'.',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'~',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'.',
				'#',
				'.',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
			],
			[
				'#',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'.',
				'#',
				'#',
			],
			[
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
				'#',
			],
		],

		TownMaps: {
			OAKHAVEN: {
				id: 'OAKHAVEN',
				label: 'Oakhaven Hamlet',
				spawnCoord: { x: 5, y: 8 },
				exitWorldPos: { x: 1, y: 1 },
				safeZone: true,
				/** @type {string[][]} */
				map: [
					['#', '#', '#', '#', '#', '#', '#', '#', '#', '#', '#', '#'],
					['#', 'B', '.', '.', '#', '#', '.', '$', 'F', '.', '.', '#'],
					['#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
					['#', '.', '#', '#', '.', '.', 'E', '.', '.', '#', '.', '#'],
					['#', '.', '#', '#', '.', '.', '.', '.', '.', '#', '.', '#'],
					['#', '.', '.', '.', '.', 'C', 'V', '.', '.', '.', '.', '#'],
					['#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
					['#', '#', '#', '#', '.', '.', '.', '.', '#', '#', '#', '#'],
					['#', '#', '#', '#', 'G', '.', '@', '.', '#', '#', '#', '#'],
					['#', '#', '#', '#', '#', 'O', 'O', '#', '#', '#', '#', '#'],
				],
			},
		},
		//#endregion

		//#region [SEC-09] Status Ailments, Quest Journal & Map Mutations
		// --- Canonical Status Ailment Registry ---
		Ailments: {
			POISON: {
				id: 'POISON',
				label: 'Poison',
				type: 'dot',
				/**
				 * Computes and applies turn damage tick for Poison.
				 * [State Mutating]
				 * @param {CharacterSnapshot} target - Target character or enemy entity.
				 * @returns {{ dmg: number, msg: string }} Tick resolution envelope.
				 */
				tick(target) {
					const maxHp = target.maxHp || 30;
					const curHp = target.hp !== undefined ? target.hp : maxHp;
					const dmg = Math.max(1, Math.round(maxHp * 0.08));
					target.hp = Math.max(0, curHp - dmg);
					return { dmg, msg: `${target.name || 'Entity'} suffered ${dmg} poison damage!` };
				},
			},
			BURN: {
				id: 'BURN',
				label: 'Burn',
				type: 'dot',
				/**
				 * Computes and applies turn damage tick for Burn.
				 * [State Mutating]
				 * @param {CharacterSnapshot} target - Target character or enemy entity.
				 * @returns {{ dmg: number, msg: string }} Tick resolution envelope.
				 */
				tick(target) {
					const dmg = 4;
					const curHp = target.hp !== undefined ? target.hp : (target.maxHp || 30);
					target.hp = Math.max(0, curHp - dmg);
					return { dmg, msg: `${target.name || 'Entity'} burned for ${dmg} damage!` };
				},
			},
			STUN: {
				id: 'STUN',
				label: 'Stun',
				type: 'skip_turn',
				/**
				 * Produces turn notification when an entity is stunned.
				 * [Pure Query]
				 * @param {CharacterSnapshot} target - Stunned character or enemy entity.
				 * @returns {{ msg: string }} Notification payload.
				 */
				tick(target) {
					return { msg: `${target.name || 'Entity'} is stunned and cannot move!` };
				},
			},
		},

		// --- Quest & Narrative Registry ---
		/** @type {Record<string, QuestDefinition>} */
		Quests: {
			SHADE_WOLF_HUNT: {
				id: 'SHADE_WOLF_HUNT',
				title: 'Trouble in the Tall Grass',
				stages: {
					0: {
						desc: 'Speak with Elder Oakhaven near the village entrance.',
						completed: false,
					},
					1: {
						desc: 'Defeat the Shade Wolf pack in the south meadows.',
						completed: false,
					},
					2: {
						desc: 'Report back to Elder Oakhaven for your reward.',
						completed: false,
					},
					3: {
						desc: 'Quest Complete. The southern roads are secure.',
						completed: true,
					},
				},
				rewards: { gold: 50, exp: 40, item: 'SWIFT_RING' },
			},
			CRYPT_KEY_SEARCH: {
				id: 'CRYPT_KEY_SEARCH',
				title: 'The Sealed Pass',
				stages: {
					0: {
						desc: 'An iron gate blocks the mountain pass. Search the southern trail for an old chest.',
						completed: false,
					},
					1: {
						desc: 'Defeat the guardians guarding the crypt key.',
						completed: false,
					},
					2: {
						desc: 'Unlock the crypt pass and report back to Elder Rowan.',
						completed: false,
					},
					3: {
						desc: 'Quest Complete. The eastern passage is open.',
						completed: true,
					},
				},
				rewards: { gold: 80, exp: 60, item: 'CHAINMAIL' },
			},
			SLAY_MALAKOR: {
				id: 'SLAY_MALAKOR',
				title: 'The Cinder Cataclysm',
				stages: {
					0: {
						desc: 'Locate the descent into the Crypt Sanctum (⛩).',
						completed: false,
					},
					1: {
						desc: 'Vanquish Malakor, The Cinder Revenant, and claim his Cinder Core.',
						completed: false,
					},
					2: {
						desc: 'Malakor is slain! The catacomb fires have been extinguished.',
						completed: true,
					},
				},
				rewards: { gold: 200, exp: 150, item: 'CINDER_CORE' },
			},
			FORGE_SABOTAGE: {
				id: 'FORGE_SABOTAGE',
				title: 'The Missing Crucible Iron',
				stages: {
					0: {
						desc: "Torvald's refined ore has been stolen. Search the town back alleys.",
						completed: false,
					},
					1: {
						desc: "Pick the lock on the smuggler's strongbox behind the Relic Crucible.",
						completed: false,
					},
					2: {
						desc: 'Return the refined crucible iron to Torvald the Blacksmith.',
						completed: false,
					},
					3: {
						desc: "Quest Complete. Torvald's supply is restored.",
						completed: true,
					},
				},
				rewards: { gold: 60, exp: 50, item: 'CHAINMAIL' },
			},
			SANCTUARY_PLAGUE: {
				id: 'SANCTUARY_PLAGUE',
				title: 'Blight in the Sanctuary',
				stages: {
					0: {
						desc: 'Tend to the afflicted scout resting at the town sanctuary camp.',
						completed: false,
					},
					1: {
						desc: 'Provide an Ether Vial or cast Holy Healing to neutralize the poison.',
						completed: false,
					},
					2: {
						desc: 'Quest Complete. The scout will survive.',
						completed: true,
					},
				},
				rewards: { gold: 40, exp: 45, item: 'SWIFT_RING' },
			},
		},

		// --- Dynamic World Map Mutations ---
		/** @type {WorldMutationDefinition[]} */
		WorldMutations: [
			{
				id: 'BRIDGE_REPAIR',
				requiresFlags: { QUEST_WOLVES_ACCEPTED: true },
				overrides: [{ x: 4, y: 1, tile: '.' }],
			},
			{
				id: 'GATE_UNLOCK',
				requiresFlags: { unlocked_crypt_gate: true },
				overrides: [{ x: 9, y: 4, tile: '.' }],
			},
			{
				id: 'LOOT_CHEST',
				requiresFlags: { looted_crypt_chest: true },
				overrides: [{ x: 9, y: 8, tile: '.' }],
			},
			{
				id: 'LOOT_OAKHAVEN_CHEST',
				requiresFlags: { looted_oakhaven_iron: true },
				overrides: [{ x: 7, y: 1, tile: '.' }],
			},
			{
				id: 'SOUTH_GATE_UNLOCK',
				requiresFlags: { unlocked_south_portcullis: true },
				overrides: [{ x: 23, y: 24, tile: '/' }],
			},
		],
		//#endregion

		//#region [SEC-10] Commercial Shops & Scripted Branching Dialogues
		// --- Merchant & Commerce District Tables ---
		Shops: {
			VILLAGE_BLACKSMITH: {
				id: 'VILLAGE_BLACKSMITH',
				label: 'Oakhaven Armory & Forge',
				merchantName: 'Torvald the Smith',
				buyRate: 1.0,
				sellRate: 0.5,
				stock: [
					{ itemId: 'POTION', maxQuantity: 10 },
					{ itemId: 'ETHER', maxQuantity: 5 },
					{ itemId: 'IRON_SWORD', maxQuantity: 2 },
					{ itemId: 'OAK_STAFF', maxQuantity: 2 },
					{ itemId: 'CHAIN_VEST', maxQuantity: 1 },
					{ itemId: 'CHAINMAIL', maxQuantity: 1 },
					{ itemId: 'MAGE_ROBE', maxQuantity: 1 },
					{ itemId: 'SWIFT_RING', maxQuantity: 1 },
				],
			},
			WANDERING_CARAVAN: {
				id: 'WANDERING_CARAVAN',
				label: 'The Nomadic Outpost',
				merchantName: 'Balthazar the Wanderer',
				buyRate: 1.1,
				sellRate: 0.65,
				stock: [
					{ itemId: 'ETHER', maxQuantity: 8 },
					{ itemId: 'PHOENIX_EMBER', maxQuantity: 3 },
					{ itemId: 'SWIFT_RING', maxQuantity: 2 },
					{ itemId: 'CHAINMAIL', maxQuantity: 1 },
				],
			},
		},

		// --- Scripted Branching Scenarios ---
		/** @type {Record<string, DialogueDefinition>} */
		Dialogues: {
			VILLAGE_ELDER: {
				id: 'VILLAGE_ELDER',
				speaker: 'Elder Oakhaven',
				nodes: [
					{
						id: 'start',
						text: 'Greetings, {leader}. Our scouts report {potions} supplies in your pouch and {gold} gold in your purse.',
						redirects: [
							{ requireFlag: 'boss_slain', target: 'boss_dead' },
							{ requireFlag: 'QUEST_WOLVES_COMPLETED', target: 'completed' },
							{
								requireQuestStage: { questId: 'SHADE_WOLF_HUNT', minStage: 1 },
								target: 'in_progress',
							},
						],
						next: 'ask_help',
					},
					{
						id: 'ask_help',
						text: 'Will your party of {partyCount} venture into the tall grass to secure the road?',
						choices: [
							{ text: 'We will protect the town.', next: 'accept' },
							{ text: 'Not at this moment.', next: 'decline' },
						],
					},
					{
						id: 'accept',
						text: 'Bless you, {leader}! Take this {item:POTION} and 20 gold. The hunt begins!',
						giveItem: 'POTION',
						giveGold: 20,
						setFlag: 'QUEST_WOLVES_ACCEPTED',
						advanceQuest: { questId: 'SHADE_WOLF_HUNT', stage: 1 },
						next: null,
					},
					{
						id: 'decline',
						text: 'Then stay vigilant. The shadows show no mercy.',
						next: null,
					},
					{
						id: 'in_progress',
						text: 'You carry {potions} {item:POTION}s and {gold} gold, {leader}. Have the wolves been dealt with?',
						choices: [
							{
								text: 'We have {potions} {item:POTION}s ready.',
								next: 'supplies_check',
								requireItem: 'POTION',
								lockReason: 'Requires 1 {item:POTION}',
							},
							{ text: 'Still tracking them.', next: 'hunting' },
						],
					},
					{
						id: 'supplies_check',
						text: 'Good preparation, {leader}. Stay focused on the south clearing.',
						next: null,
					},
					{
						id: 'hunting',
						text: 'May the ember protect all {partyCount} of you.',
						next: null,
					},
					{
						id: 'completed',
						text: 'The southern road is quiet. Now look to the east—the Crypt Sanctum stirs with primordial fire.',
						next: null,
					},
					{
						id: 'boss_dead',
						text: 'Malakor has fallen! The sky cleared over Oakhaven. You carry the Cinder Core—a true legend of the Ember.',
						next: null,
					},
				],
			},
			ELDER_GREETING: {
				id: 'ELDER_GREETING',
				speaker: 'Elder Rowan',
				nodes: [
					{
						id: 'start',
						text: 'Greetings, travelers. The old iron gate to the east seals the Whispering Crypt. Search the old chest along the southern tree line for the key.',
						choices: [
							{ text: 'We will find the key.', next: 'accept' },
							{ text: 'What monsters lurk within?', next: 'warn' },
						],
					},
					{
						id: 'accept',
						text: 'May the light guide your blade. Rest at camp before you proceed.',
						setFlag: 'QUEST_CRYPT_ACCEPTED',
						next: null,
					},
					{
						id: 'warn',
						text: 'Skeletons that resist light steel, and venomous spiders. Prepare your party well.',
						next: null,
					},
				],
			},
			TOWN_GUARD: {
				id: 'TOWN_GUARD',
				speaker: 'Captain Kael',
				nodes: [
					{
						id: 'start',
						text: 'Halt, {leader}. The roads south are infested with shade wolves.',
						redirects: [
							{ requireFlag: 'QUEST_WOLVES_COMPLETED', target: 'veteran' },
							{ requireFlag: 'QUEST_WOLVES_ACCEPTED', target: 'caution' },
						],
						choices: [
							{ text: 'We are ready to clear the path.', next: 'rally' },
							{ text: 'Who maintains these gates?', next: 'lore' },
						],
					},
					{
						id: 'rally',
						text: 'Speak with Elder Rowan near the town square before you step beyond the palisade.',
						next: null,
					},
					{
						id: 'lore',
						text: 'The Oakhaven guard. We hold the perimeter against the catacomb ashes.',
						next: null,
					},
					{
						id: 'caution',
						text: 'Keep your weapons drawn, {leader}. The wolves strike without sound in the tall grass.',
						next: null,
					},
					{
						id: 'veteran',
						text: 'You cleared the south roads! The town owes your party of {partyCount} its survival.',
						next: null,
					},
				],
			},
			AFFLICTED_SCOUT: {
				id: 'AFFLICTED_SCOUT',
				speaker: 'Afflicted Scout',
				nodes: [
					{
						id: 'start',
						text: 'Ugh... the catacomb spiders... their venom burns like liquid ash...',
						redirects: [{ requireFlag: 'scout_healed', target: 'cured' }],
						choices: [
							{
								text: 'Administer 1 {item:ETHER} to cleanse the venom.',
								next: 'heal_ether',
								requireItem: 'ETHER',
								lockReason: 'Requires 1 {item:ETHER}',
							},
							{ text: 'Hold on, we will find help.', next: 'end' },
						],
					},
					{
						id: 'heal_ether',
						text: 'The cool ether halts the venom! Bless you... Take this ring I recovered from the crypts.',
						takeItem: 'ETHER',
						setFlag: 'scout_healed',
						giveItem: 'SWIFT_RING',
						giveGold: 30,
						completeQuest: 'SANCTUARY_PLAGUE',
						next: null,
					},
					{
						id: 'cured',
						text: 'My breathing is steady again. Be careful near the eastern crypt stairs, {leader}.',
						next: null,
					},
					{
						id: 'end',
						text: 'Hurry... the shadow spreads fast...',
						next: null,
					},
				],
			},
		},
		//#endregion

		//#region [SEC-11] Domain Stat Calculators & Projection Kernels
		/**
		 * Pure domain calculation aggregating net stat bonuses from all equipped items.
		 * [Pure Query]
		 * @param {CharacterSnapshot|null|undefined} character - Target character instance.
		 * @returns {BaseStats} Aggregated attribute modifier dictionary.
		 */
		calculateGearStats(character) {
			/** @type {BaseStats} */
			const totals = { hp: 0, mp: 0, atk: 0, def: 0, agi: 0 };
			if (!character?.equipment) return totals;

			/** @type {Array<'weapon'|'armor'|'accessory'>} */
			const slots = ['weapon', 'armor', 'accessory'];
			slots.forEach((slotKey) => {
				const equippedId = character.equipment?.[slotKey];
				if (equippedId && manifest.Items?.[equippedId]?.statDeltas) {
					const deltas = manifest.Items[equippedId].statDeltas;
					if (deltas) {
						Object.entries(deltas).forEach(([stat, val]) => {
							if (val && typeof val === 'number') {
								totals[/** @type {keyof BaseStats} */ (stat)] = (totals[/** @type {keyof BaseStats} */ (stat)] || 0) + val;
							}
						});
					}
				}
			});
			return totals;
		},

		/**
		 * Pure domain projection computing total effective attributes from base, growths, Aether nodes, and equipment.
		 * [Pure Query]
		 * @param {CharacterSnapshot|null|undefined} character - Target character instance.
		 * @returns {CharacterStats} Fully hydrated authoritative stat block.
		 */
		computeCharacterStats(character) {
			const phenoKey = character?.phenotype || 'HERO';
			const pheno = manifest.Phenotypes?.[phenoKey] || {};
			const base = pheno.baseStats || {
				hp: 30,
				mp: 10,
				atk: 8,
				def: 5,
				agi: 5,
			};
			const growth = pheno.growth || { hp: 4, mp: 2, atk: 1, def: 1, agi: 1 };
			const levelGains = Math.max(0, (character?.level || 1) - 1);

			/** @type {CharacterStats} */
			const totals = {
				hp: base.hp + growth.hp * levelGains,
				maxHp: base.hp + growth.hp * levelGains,
				mp: base.mp + growth.mp * levelGains,
				maxMp: base.mp + growth.mp * levelGains,
				atk: base.atk + growth.atk * levelGains,
				def: base.def + growth.def * levelGains,
				agi: base.agi + growth.agi * levelGains,
			};

			const graph = manifest.AetherNodes || {};
			const unlocked = character?.unlockedNodes || character?.unlocked || [];
			unlocked.forEach((nodeId) => {
				const node = graph[nodeId];
				if (node?.statDeltas) {
					Object.entries(node.statDeltas).forEach(([stat, val]) => {
						if (val && typeof val === 'number') {
							const key = /** @type {keyof CharacterStats} */ (stat);
							totals[key] = (totals[key] || 0) + val;
							if (stat === 'hp') totals.maxHp = (totals.maxHp || 0) + val;
							if (stat === 'mp') totals.maxMp = (totals.maxMp || 0) + val;
						}
					});
				}
			});

			const gear = manifest.calculateGearStats(character);
			totals.hp += gear.hp;
			totals.maxHp += gear.hp;
			totals.mp += gear.mp;
			totals.maxMp += gear.mp;
			totals.atk += gear.atk;
			totals.def += gear.def;
			totals.agi += gear.agi;

			return totals;
		},

		/**
		 * Pure domain projection generating a fresh map matrix with active dynamic chronicle overrides applied.
		 * [Pure Query]
		 * @param {string[][]} baseMap - Input 2D tile matrix.
		 * @param {Record<string, boolean>} [flags={}] - Active story flags snapshot.
		 * @returns {string[][]} Projected 2D tile matrix with applied mutations.
		 */
		getResolvedMap(baseMap, flags = {}) {
			if (!baseMap || !Array.isArray(baseMap)) return baseMap;
			const resolved = baseMap.map((row) => [...row]);
			const mutations = manifest.WorldMutations || [];
			mutations.forEach((mutation) => {
				if (mutation.flag && flags[mutation.flag]) {
					const { targetX, targetY, replacementTile } = mutation;
					if (targetX !== undefined && targetY !== undefined && replacementTile !== undefined) {
						if (resolved[targetY]?.[targetX] !== undefined) {
							resolved[targetY][targetX] = replacementTile;
						}
					}
				}
				if (mutation.requiresFlags) {
					const match = Object.entries(mutation.requiresFlags).every(
						([f, expected]) => flags[f] === expected
					);
					if (match && Array.isArray(mutation.overrides)) {
						mutation.overrides.forEach(({ x, y, tile }) => {
							if (resolved[y]?.[x] !== undefined) {
								resolved[y][x] = tile;
							}
						});
					}
				}
			});
			return resolved;
		},
		//#endregion
	};

	//#region [SEC-12] Immutability Sealing & Runtime Module Exports
	// Alias Classes to Phenotypes for full backward compatibility across legacy callers
	manifest.Classes = manifest.Phenotypes;

	/**
	 * Recursively freezes an object tree to guarantee strict runtime immutability.
	 * [State Mutating / Deep Freeze]
	 * @template T
	 * @param {T} obj - Object graph to seal.
	 * @returns {Readonly<T>} Immutable reference to sealed object graph.
	 */
	function deepFreeze(obj) {
		if (!obj || typeof obj !== 'object') return obj;
		Object.keys(obj).forEach((prop) => {
			const val = /** @type {Record<string, any>} */ (obj)[prop];
			if (typeof val === 'object' && val !== null && !Object.isFrozen(val)) {
				deepFreeze(val);
			}
		});
		return Object.freeze(obj);
	}

	return deepFreeze(manifest);
})();

if (typeof window !== 'undefined') {
	window['EmberlightManifest'] = EmberlightManifest;
}
if (typeof module !== 'undefined' && module.exports) {
	module.exports = EmberlightManifest;
}
//#endregion