/**
 * ============================================================================
 * PHOENIX SOVEREIGN TYPE RESOLVER & JSDOC CONTRACT SCAFFOLDER
 * Document Identifier: VLT-003-PHOENIX-TYPE-RESOLVER
 * Governing Protocol:  VSRP-001 / MPFS-001 / PSGC-001 [SEC-01.2]
 * Authority:           Host SSOT | Zero-Dependency Ambient Type Indexer & Inferrer
 * ============================================================================
 *
 * CMD-DOC-INDEX (Auto-Regenerated by AOP-VALIDATOR-002 -- Do Not Edit Manually)
 * =============================================================================
 * [SEC-01] Semantic Dictionaries, In-Memory Catalogs & Type Mappings .. Line ~0023
 * [SEC-02] Ambient JSDoc Parser & Nested Signature Lexical Scanner .. Line ~0150
 * [SEC-03] TypeScript (.d.ts) Declaration Ingestion & Interface Scanner .. Line ~0342
 * [SEC-04] Parameter Type Inference Engine ...................... Line ~0433
 * [SEC-05] Return Type & Expression Inference Engine ............ Line ~0595
 * [SEC-06] Contract Synthesis Engine & Strict JSDoc Block Formatter .. Line ~0900
 * [SEC-07] Document AST Line Scaffolder, Catalog Loader & Sovereign Membrane .. Line ~1113
 * =============================================================================
 */
((/** @type {Record<string, unknown>} */ global) => {
	'use strict';

	//#region [SEC-01] Semantic Dictionaries, In-Memory Catalogs & Type Mappings
	/**
	 * Canonical Parameter Semantic Dictionary.
	 * Maps common sovereign domain tokens to their canonical phoenix.d.ts types and descriptions.
	 * @type {Record<string, { type: string; desc: string }>}
	 */
	const DOMAIN_TYPE_DICTIONARY = Object.freeze({
		// Phoenix Governance & DTOs
		proposal: { type: 'PhoenixProposalDTO', desc: 'PGE-DSL-1 proposal envelope to evaluate' },
		prop: { type: 'PhoenixProposalDTO', desc: 'Target proposal envelope' },
		receipt: { type: 'PhoenixReceiptDTO', desc: 'Immutable PGE-RECEIPT-1 cryptographic evaluation receipt' },
		change: { type: 'PhoenixChangeDTO', desc: 'Atomic file or AST change directive' },
		changes: { type: 'PhoenixChangeDTO[]', desc: 'Ordered array of change directives' },
		governor: { type: 'PhoenixGovernorInstance', desc: 'Target sovereign governor instance' },
		gov: { type: 'PhoenixGovernorInstance', desc: 'Governor instance reference' },
		cartridge: { type: 'VSRPCartridgeFacade', desc: 'Active running VSRP-001 cartridge instance' },
		ast: { type: 'CartridgeAST | Record<string, unknown>', desc: 'Structured AST representation' },

		// Virtual Filesystem & Storage
		vfs: { type: 'Map<string, string>', desc: 'Virtual file system storage map' },
		vfsMap: { type: 'Map<string, string>', desc: 'Virtual file system map' },
		filePath: { type: 'string', desc: 'Target file path in the sovereign workspace' },
		path: { type: 'string', desc: 'Resource or module path' },
		code: { type: 'string', desc: 'JavaScript or cartridge source code' },
		source: { type: 'string', desc: 'Raw source code string' },
		content: { type: 'string', desc: 'Text or document content' },

		// Canvas & Graphics Substrates
		ctx: { type: 'CanvasRenderingContext2D', desc: '2D canvas rendering context' },
		canvas: { type: 'HTMLCanvasElement', desc: 'Target viewport canvas element' },
		gl: { type: 'WebGLRenderingContext', desc: 'WebGL rendering context' },
		camera: { type: 'PhoenixCamera2D | { x: number; y: number; zoom: number }', desc: 'Viewport camera state' },
		entId: { type: 'string', desc: 'Target entity unique identifier' },
		entityId: { type: 'string', desc: 'Unique scene entity identifier' },
		tileId: { type: 'number', desc: 'Numeric tile palette identifier' },
		tierKey: { type: "'canvas2d' | 'voxel3d' | 'terrain3d' | 'webgl'", desc: 'Rendering engine tier identifier' },

		// Primitives & General Coordinates
		lineNum: { type: 'number', desc: '1-indexed line number' },
		line: { type: 'number', desc: '1-indexed line offset' },
		col: { type: 'number', desc: '1-indexed column offset' },
		column: { type: 'number', desc: '1-indexed column offset' },
		x: { type: 'number', desc: 'X-axis coordinate' },
		y: { type: 'number', desc: 'Y-axis coordinate' },
		z: { type: 'number', desc: 'Z-axis coordinate' },
		width: { type: 'number', desc: 'Width in pixels' },
		height: { type: 'number', desc: 'Height in pixels' },
		w: { type: 'number', desc: 'Width dimension' },
		h: { type: 'number', desc: 'Height dimension' },
		count: { type: 'number', desc: 'Item count or quantity' },
		timeout: { type: 'number', desc: 'Timeout in milliseconds' },
		timeoutMs: { type: 'number', desc: 'Execution timeout in milliseconds' },
		timestamp: { type: 'number', desc: 'High-resolution performance timestamp' },
		ts: { type: 'number', desc: 'Timestamp value' },
		fps: { type: 'number', desc: 'Frames per second target rate' },

		// Identifiers & Strings
		id: { type: 'string', desc: 'Unique entity or item identifier' },
		name: { type: 'string', desc: 'Descriptive identifier or name' },
		fnName: { type: 'string', desc: 'Target function name' },
		key: { type: 'string', desc: 'Key or identifier token' },
		msg: { type: 'string', desc: 'Informational or error message' },
		rawText: { type: 'string', desc: 'Raw unparsed text content' },
		query: { type: 'string', desc: 'Search query string' },

		// DOM & Events
		e: { type: 'Event | KeyboardEvent | MouseEvent', desc: 'DOM event object' },
		evt: { type: 'Event', desc: 'Triggered event instance' },
		event: { type: 'Event', desc: 'DOM event instance' },
		el: { type: 'HTMLElement', desc: 'Target DOM element' },
		element: { type: 'HTMLElement', desc: 'Target DOM element' },

		// Data structures & Options
		options: { type: 'Record<string, unknown>', desc: 'Optional configuration settings' },
		opts: { type: 'Record<string, unknown>', desc: 'Execution options' },
		config: { type: 'Record<string, unknown>', desc: 'Configuration dictionary' },
		params: { type: 'string[]', desc: 'Parameter names list' },
		items: { type: 'PhoenixSymbolItem[] | unknown[]', desc: 'Collection of elements' },
		list: { type: 'unknown[]', desc: 'List of records' },
		lines: { type: 'string[]', desc: 'Array of source code lines' },
		tokens: { type: 'LexerTokenDTO[] | SynarcheToken[]', desc: 'Token stream array' },
		token: { type: 'LexerTokenDTO | SynarcheToken', desc: 'Lexical token descriptor' },

		// Callbacks & Predicates
		cb: { type: '(...args: unknown[]) => void', desc: 'Callback function' },
		callback: { type: '(...args: unknown[]) => void', desc: 'Completion callback handler' },
		handler: { type: '(...args: unknown[]) => void', desc: 'Event handler callback' },
		predicate: { type: '(item: unknown) => boolean', desc: 'Filtering predicate function' },

		// VLT Compliance & Anchors
		anchorId: { type: 'string', desc: 'Canonical section anchor identifier, e.g. [SEC-01]' },
		regions: { type: 'VLTRegionInfo[]', desc: 'Array of scanned region descriptors' },
		violations: { type: 'VLTComplianceViolation[]', desc: 'Array of compliance violations' },
		report: { type: 'VLTComplianceReport', desc: 'Comprehensive VLT compliance report' },

		// Error Resolution Ledger & Remediation
		erl: { type: 'PhoenixErrorResolutionLedgerInstance', desc: 'Error Resolution Ledger instance' },
		record: { type: 'ERLResolutionRecordDTO | Record<string, unknown>', desc: 'Resolution record' },
		pattern: { type: 'ERLPatternDTO | Record<string, unknown>', desc: 'Error matching pattern descriptor' },

		// Symbols & Indexer
		indexer: { type: 'PhoenixSymbolIndexerFacade & PhoenixSymbolIndexerSingleton', desc: 'Symbol indexer instance or singleton' },
		symbol: { type: 'PhoenixSymbolItem', desc: 'Indexed symbol descriptor' },
		symbols: { type: 'PhoenixSymbolItem[]', desc: 'Collection of indexed symbols' },

		// Diff Engine & Scaffolding
		diff: { type: 'ChunkDiffResultDTO', desc: 'Chunk diff calculation result' },
		contract: { type: 'PhoenixInferredContract', desc: 'Inferred function contract' },
		resolver: { type: 'PhoenixTypeResolverFacade', desc: 'Phoenix type resolver facade' }
	});

	/**
	 * In-memory index of parsed declarations from phoenix.d.ts.
	 * Maps method and function names to their parameter and return signatures.
	 * @type {Map<string, { params: Array<{ name: string; type: string; optional: boolean; desc?: string }>; returnType: string; desc?: string }>}
	 */
	const _methodCatalog = new Map();

	/**
	 * In-memory index of declared interfaces and types.
	 * @type {Map<string, { desc?: string; properties: Record<string, string> }>}
	 */
	const _interfaceCatalog = new Map();

	let _catalogInitialized = false;
	//#endregion [SEC-01]

	//#region [SEC-02] Ambient JSDoc Parser & Nested Signature Lexical Scanner
	/**
	 * Parses a JSDoc @param line into name, type, and description.
	 * [Pure Function] Complexity <= 6.
	 * @param {string} line - Cleaned JSDoc line starting with @param
	 * @returns {{ name: string; type: string; desc: string } | null}
	 * @private
	 */
	function _parseParamTag(line) {
		const body = line.slice(6).trim();
		let rest = body;
		let type = '';
		if (rest.startsWith('{')) {
			const closeIdx = rest.indexOf('}');
			if (closeIdx !== -1) {
				type = rest.slice(1, closeIdx).trim();
				rest = rest.slice(closeIdx + 1).trim();
			}
		}
		const nameMatch = /^\[?([A-Za-z0-9_$]+)(?:=[^\]]+)?\]?/.exec(rest);
		if (!nameMatch) return null;
		const name = nameMatch[ 1 ];
		let desc = rest.slice(nameMatch[ 0 ].length).trim();
		if (desc.startsWith('-')) desc = desc.slice(1).trim();
		return { name, type, desc };
	}

	/**
	 * Parses a JSDoc @returns line into type and description.
	 * [Pure Function] Complexity <= 4.
	 * @param {string} line - Cleaned JSDoc line starting with @return or @returns
	 * @returns {{ type: string; desc: string }}
	 * @private
	 */
	function _parseReturnTag(line) {
		const body = line.replace(/^@returns?\s*/, '').trim();
		let type = '';
		let desc = body;
		if (desc.startsWith('{')) {
			const closeIdx = desc.indexOf('}');
			if (closeIdx !== -1) {
				type = desc.slice(1, closeIdx).trim();
				desc = desc.slice(closeIdx + 1).trim();
			}
		}
		if (desc.startsWith('-')) desc = desc.slice(1).trim();
		return { type, desc };
	}

	/**
	 * Updates parsed JSDoc descriptor based on a single stripped comment line.
	 * [State-Mutating Helper] Complexity <= 4.
	 * @param {string} cleaned - Cleaned JSDoc comment line
	 * @param {{ desc: string; paramDescriptions: Record<string, string>; returnDesc: string }} parsedDoc
	 * @private
	 */
	function _processJSDocLine(cleaned, parsedDoc) {
		if (cleaned.startsWith('@param')) {
			const parsed = _parseParamTag(cleaned);
			if (parsed) {
				parsedDoc.paramDescriptions[ parsed.name ] = parsed.desc;
			}
			return;
		}
		if (cleaned.startsWith('@returns') || cleaned.startsWith('@return')) {
			const parsed = _parseReturnTag(cleaned);
			parsedDoc.returnDesc = parsed.desc;
			return;
		}
		if (!cleaned.startsWith('@') && !parsedDoc.desc) {
			parsedDoc.desc = cleaned;
		}
	}

	/**
	 * Extracts docstring description and tags above a declaration.
	 * [Pure Function] Complexity <= 4.
	 * @param {string} rawComment - JSDoc comment text
	 * @returns {{ desc: string; paramDescriptions: Record<string, string>; returnDesc: string }}
	 * @private
	 */
	function _parseJSDocBlock(rawComment) {
		const parsedDoc = { desc: '', paramDescriptions: {}, returnDesc: '' };
		const lines = rawComment.split('\n');
		for (const line of lines) {
			const cleaned = line.replace(/^\s*\/?\*+\/?\s*/, '').trim();
			if (cleaned) {
				_processJSDocLine(cleaned, parsedDoc);
			}
		}
		return parsedDoc;
	}

	/**
	 * Updates bracket depth counters for nested signature argument splitting.
	 * [Pure Helper] Complexity <= 6.
	 * @param {string} ch
	 * @param {{ angle: number; paren: number; brace: number }} depths
	 * @private
	 */
	function _updateSignatureNesting(ch, depths) {
		if (ch === '<') { depths.angle++; return; }
		if (ch === '>') { depths.angle = Math.max(0, depths.angle - 1); return; }
		if (ch === '(') { depths.paren++; return; }
		if (ch === ')') { depths.paren = Math.max(0, depths.paren - 1); return; }
		if (ch === '{') { depths.brace++; return; }
		if (ch === '}') { depths.brace = Math.max(0, depths.brace - 1); }
	}

	/**
	 * Determines if character cursor is outside all nested brackets.
	 * [Pure Helper] Complexity <= 2.
	 * @param {{ angle: number; paren: number; brace: number }} depths
	 * @returns {boolean}
	 * @private
	 */
	function _isSignatureTopLevel(depths) {
		return depths.angle === 0 && depths.paren === 0 && depths.brace === 0;
	}

	/**
	 * Splits argument strings respecting nested brackets <>, (), and {}.
	 * [Pure Function] Complexity <= 6.
	 * @param {string} str - Raw comma-separated parameter string
	 * @returns {string[]}
	 * @private
	 */
	function _splitSignatureArgs(str) {
		const results = [];
		let current = '';
		const depths = { angle: 0, paren: 0, brace: 0 };

		for (const ch of str) {
			_updateSignatureNesting(ch, depths);
			if (ch === ',' && _isSignatureTopLevel(depths)) {
				results.push(current.trim());
				current = '';
			} else {
				current += ch;
			}
		}
		if (current.trim()) {
			results.push(current.trim());
		}
		return results;
	}

	/**
	 * Finds the JSDoc comment immediately preceding a character index in source.
	 * [Pure Function] Complexity <= 4.
	 * @param {string} content
	 * @param {number} index
	 * @returns {string}
	 * @private
	 */
	function _findPrecedingDoc(content, index) {
		const preceding = content.slice(Math.max(0, index - 1000), index).trimEnd();
		if (preceding.endsWith('*/')) {
			const commentStart = preceding.lastIndexOf('/**');
			if (commentStart !== -1) {
				return preceding.slice(commentStart + 3, - 2);
			}
		}
		return '';
	}

	/**
	 * Parses parameter declarations from raw parameter string.
	 * [Pure Function] Complexity <= 6.
	 * @param {string} rawParams
	 * @param {Record<string, string>} paramDescriptions
	 * @returns {Array<{ name: string; type: string; optional: boolean; desc: string }>}
	 * @private
	 */
	function _parseMethodParams(rawParams, paramDescriptions) {
		if (!rawParams) return [];
		return _splitSignatureArgs(rawParams).map(p => {
			const colonIdx = p.indexOf(':');
			const namePart = colonIdx !== -1 ? p.slice(0, colonIdx).trim() : p.trim();
			const typePart = colonIdx !== -1 ? p.slice(colonIdx + 1).trim() : 'unknown';
			const isOptional = namePart.endsWith('?');
			const cleanName = isOptional ? namePart.slice(0, -1) : namePart;
			return {
				name: cleanName,
				type: typePart,
				optional: isOptional,
				desc: paramDescriptions[ cleanName ] || ''
			};
		});
	}
	//#endregion [SEC-02]

	//#region [SEC-03] TypeScript (.d.ts) Declaration Ingestion & Interface Scanner
	/**
	 * Indexes a single method regex match into the method catalog.
	 * [State-Mutating Helper] Complexity <= 2.
	 * @param {RegExpExecArray} match
	 * @param {string} dtsContent
	 * @private
	 */
	function _indexMethodSignature(match, dtsContent) {
		const rawDoc = _findPrecedingDoc(dtsContent, match.index);
		const methodName = match[ 1 ];
		const rawParams = match[ 2 ].trim();
		const rawReturnType = match[ 3 ].trim();

		const doc = _parseJSDocBlock(rawDoc);
		const params = _parseMethodParams(rawParams, doc.paramDescriptions);

		_methodCatalog.set(methodName, {
			params,
			returnType: rawReturnType,
			desc: doc.desc
		});
	}

	/**
	 * Indexes a single interface regex match into the interface catalog.
	 * [State-Mutating Helper] Complexity <= 2.
	 * @param {RegExpExecArray} ifMatch
	 * @param {string} dtsContent
	 * @private
	 */
	function _indexInterfaceDeclaration(ifMatch, dtsContent) {
		const ifDoc = _parseJSDocBlock(_findPrecedingDoc(dtsContent, ifMatch.index));
		const ifName = ifMatch[ 1 ];
		_interfaceCatalog.set(ifName, {
			desc: ifDoc.desc,
			properties: {}
		});
	}

	/**
	 * Scans and indexes all method signatures from .d.ts content.
	 * [State-Mutating Helper] Complexity <= 2.
	 * @param {string} dtsContent
	 * @returns {number}
	 * @private
	 */
	function _scanMethodSignatures(dtsContent) {
		const methodRegex = /\b([\w$]+)\s*\(([^)]*)\)\s*:\s*([^;\x7B\r\n]+)/g;
		let match;
		let count = 0;
		while ((match = methodRegex.exec(dtsContent)) !== null) {
			_indexMethodSignature(match, dtsContent);
			count++;
		}
		return count;
	}

	/**
	 * Scans and indexes all interface declarations from .d.ts content.
	 * [State-Mutating Helper] Complexity <= 2.
	 * @param {string} dtsContent
	 * @private
	 */
	function _scanInterfaceDeclarations(dtsContent) {
		const interfaceRegex = /declare\s+(?:interface|type)\s+([A-Za-z0-9_$]+)/g;
		let ifMatch;
		while ((ifMatch = interfaceRegex.exec(dtsContent)) !== null) {
			_indexInterfaceDeclaration(ifMatch, dtsContent);
		}
	}

	/**
	 * Parses TypeScript ambient declarations (.d.ts) into the in-memory symbol catalog.
	 * [State-Mutating Function] Complexity <= 3.
	 * @param {string} dtsContent - Raw contents of phoenix.d.ts
	 * @returns {number} Number of indexed method signatures
	 */
	function ingestDeclarations(dtsContent) {
		if (!dtsContent || typeof dtsContent !== 'string') return 0;
		_methodCatalog.clear();
		_interfaceCatalog.clear();

		const count = _scanMethodSignatures(dtsContent);
		_scanInterfaceDeclarations(dtsContent);

		_catalogInitialized = true;
		return count;
	}
	//#endregion [SEC-03]

	//#region [SEC-04] Parameter Type Inference Engine
	/**
	 * Table mapping parameter suffix patterns to canonical typed array descriptors.
	 * @type {ReadonlyArray<[RegExp, string]>}
	 */
	const _ARRAY_PARAM_TYPE_MAP = Object.freeze([
		[ /tokens?$/i, 'LexerTokenDTO[] | SynarcheToken[]' ],
		[ /symbols?$/i, 'PhoenixSymbolItem[]' ],
		[ /lines?$/i, 'string[]' ],
		[ /changes?$/i, 'PhoenixChangeDTO[]' ],
		[ /regions?$/i, 'VLTRegionInfo[]' ],
		[ /violations?$/i, 'VLTComplianceViolation[]' ],
		[ /(?:errors?|messages?)$/i, 'string[]' ]
	]);

	/**
	 * Tests if function body exhibits array iteration or indexing patterns on target parameter.
	 * [Pure Helper] Complexity <= 3.
	 * @param {string} escaped
	 * @param {string} bodyText
	 * @returns {boolean}
	 * @private
	 */
	function _hasArrayUsageInBody(escaped, bodyText) {
		const arrayPattern = new RegExp(String.raw`\b${escaped}\s*\.(?:map|forEach|filter|reduce|push|pop|shift|unshift|slice|includes|indexOf|find|findIndex)\s*\(`, 'm');
		if (arrayPattern.test(bodyText)) return true;
		const arrayIndexPattern = new RegExp(String.raw`\b${escaped}\s*\[\s*[A-Za-z0-9_$]+\s*\]`);
		const arrayLengthPattern = new RegExp(String.raw`\b${escaped}\.length\b`);
		return arrayIndexPattern.test(bodyText) && arrayLengthPattern.test(bodyText);
	}

	/**
	 * Resolves specific array type based on parameter naming conventions.
	 * [Pure Helper] Complexity <= 3.
	 * @param {string} paramName
	 * @returns {string}
	 * @private
	 */
	function _resolveArrayParamType(paramName) {
		for (const [ pattern, typeName ] of _ARRAY_PARAM_TYPE_MAP) {
			if (pattern.test(paramName)) return typeName;
		}
		return 'unknown[]';
	}

	/**
	 * Infers array type of a parameter based on method calls and name heuristics.
	 * [Pure Function] Complexity <= 3.
	 * @param {string} paramName
	 * @param {string} escaped
	 * @param {string} bodyText
	 * @returns {string | null}
	 * @private
	 */
	function _inferArrayParam(paramName, escaped, bodyText) {
		if (!_hasArrayUsageInBody(escaped, bodyText)) {
			return null;
		}
		return _resolveArrayParamType(paramName);
	}

	/**
	 * Infers primitive type of a parameter (string, number, boolean).
	 * [Pure Function] Complexity <= 7.
	 * @param {string} escaped
	 * @param {string} bodyText
	 * @returns {string | null}
	 * @private
	 */
	function _inferPrimitiveParam(escaped, bodyText) {
		const strPattern = new RegExp(String.raw`\b${escaped}\s*\.(?:trim|split|toLowerCase|toUpperCase|substring|slice|startsWith|endsWith|replace|replaceAll|match)\s*\(`, 'm');
		const strTypeofPattern = new RegExp(String.raw`typeof\s+${escaped}\s*===?\s*['"]string['"]`);
		if (strPattern.test(bodyText) || strTypeofPattern.test(bodyText)) {
			return 'string';
		}

		const numPattern = new RegExp(String.raw`Math\.[A-Za-z]+\([^)]*\b${escaped}\b|\b${escaped}\s*(?:[+\-*/%]\s*\d|>=|<=|>|<|\+\+|--)`, 'm');
		const numTypeofPattern = new RegExp(String.raw`typeof\s+${escaped}\s*===?\s*['"]number['"]`);
		if (numPattern.test(bodyText) || numTypeofPattern.test(bodyText)) {
			return 'number';
		}

		const boolTypeofPattern = new RegExp(String.raw`typeof\s+${escaped}\s*===?\s*['"]boolean['"]`);
		if (boolTypeofPattern.test(bodyText)) {
			return 'boolean';
		}

		return null;
	}

	/**
	 * Infers callback or predicate function signature from parameter usage.
	 * [Pure Helper] Complexity <= 4.
	 * @param {string} paramName
	 * @param {string} escaped
	 * @param {string} bodyText
	 * @returns {string | null}
	 * @private
	 */
	function _matchCallableParam(paramName, escaped, bodyText) {
		const fnPattern = new RegExp(String.raw`\b${escaped}\s*\(|\b${escaped}\s*\.(?:call|apply|bind)\s*\(`, 'm');
		const fnTypeofPattern = new RegExp(String.raw`typeof\s+${escaped}\s*===?\s*['"]function['"]`);
		if (!fnPattern.test(bodyText) && !fnTypeofPattern.test(bodyText)) return null;
		if (/predicate|filter/i.test(paramName)) return '(item: unknown) => boolean';
		return '(...args: unknown[]) => unknown';
	}

	/**
	 * Infers function or collection type of a parameter.
	 * [Pure Function] Complexity <= 5.
	 * @param {string} paramName
	 * @param {string} escaped
	 * @param {string} bodyText
	 * @returns {string | null}
	 * @private
	 */
	function _inferFunctionParam(paramName, escaped, bodyText) {
		const callableType = _matchCallableParam(paramName, escaped, bodyText);
		if (callableType) return callableType;

		if (new RegExp(String.raw`\b${escaped}\s*\.(?:get|set|has|delete)\s*\(`).test(bodyText)) {
			return 'Map<string, unknown>';
		}

		const objPattern = new RegExp(String.raw`\bObject\.(?:keys|values|entries|assign)\s*\(\s*${escaped}\s*[),]|(?:^|[^\w.])${escaped}\.[A-Za-z0-9_$]+`);
		if (objPattern.test(bodyText)) {
			return 'Record<string, unknown>';
		}

		return null;
	}

	/**
	 * Infers type of a parameter from function body usage heuristics.
	 * Slices the first 50 lines of the function implementation.
	 * [Pure Function] Complexity <= 6.
	 * @param {string} paramName - Parameter identifier
	 * @param {string[]} bodyLines - Lines of function implementation
	 * @returns {string | null} Inferred type or null if indeterminate
	 * @private
	 */
	function _inferParamFromBody(paramName, bodyLines) {
		const escaped = paramName.replace(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);
		const bodyText = bodyLines.slice(0, 50).join('\n');

		const arrayType = _inferArrayParam(paramName, escaped, bodyText);
		if (arrayType) return arrayType;

		const primitiveType = _inferPrimitiveParam(escaped, bodyText);
		if (primitiveType) return primitiveType;

		const fnOrObjType = _inferFunctionParam(paramName, escaped, bodyText);
		if (fnOrObjType) return fnOrObjType;

		if (/(?:Source|Text|Content|Str|Raw|Html|Markdown|Input|Output|Label|Title|Message|Description)$/.test(paramName)) {
			return 'string';
		}

		return null;
	}
	//#endregion [SEC-04]

	//#region [SEC-05] Return Type & Expression Inference Engine
	/**
	 * Tests if expression evaluates to a boolean primitive.
	 * [Pure Function] Complexity <= 3.
	 * @param {string} e
	 * @returns {boolean}
	 * @private
	 */
	function _isBooleanExpr(e) {
		return e === 'true' || e === 'false' || e.startsWith('Boolean(') || e.startsWith('!') || /[<>=!]/.test(e);
	}

	/**
	 * Tests if expression evaluates to a string primitive.
	 * [Pure Function] Complexity <= 2.
	 * @param {string} e
	 * @returns {boolean}
	 * @private
	 */
	function _isStringExpr(e) {
		return e.startsWith("'") || e.startsWith('"') || e.startsWith('`') || e.startsWith('String(');
	}

	/**
	 * Tests if expression evaluates to a number primitive.
	 * [Pure Function] Complexity <= 2.
	 * @param {string} e
	 * @returns {boolean}
	 * @private
	 */
	function _isNumberExpr(e) {
		return /^-?\d+(?:\.\d+)?$/.test(e) || e.startsWith('Number(') || e.startsWith('Math.');
	}

	/**
	 * Tests if expression evaluates to an array.
	 * [Pure Function] Complexity <= 2.
	 * @param {string} e
	 * @returns {boolean}
	 * @private
	 */
	function _isArrayExpr(e) {
		return e.startsWith('[') || e.includes('.map(') || e.includes('.filter(');
	}

	/**
	 * Tests if expression evaluates to an object.
	 * [Pure Function] Complexity <= 2.
	 * @param {string} e
	 * @returns {boolean}
	 * @private
	 */
	function _isObjectExpr(e) {
		return e.startsWith('\x7B') || e.startsWith('Object.assign') || e.startsWith('Object.freeze');
	}

	/**
	 * Wraps a base type in a Promise if async context is active.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} typeName
	 * @param {boolean} isAsync
	 * @returns {string}
	 * @private
	 */
	function _wrapAsyncType(typeName, isAsync) {
		return isAsync ? `Promise<${typeName}>` : typeName;
	}

	/**
	 * Named pattern table for domain-specific array return types.
	 * @type {ReadonlyArray<{ pattern: RegExp; baseType: string; desc: string }>}
	 */
	const _ARRAY_RETURN_PATTERNS = Object.freeze([
		{ pattern: /(?:get|find|scan)?Tokens$/i, baseType: 'LexerTokenDTO[]', desc: 'Array of lexical tokens' },
		{ pattern: /(?:get|find)?Symbols$/i, baseType: 'PhoenixSymbolItem[]', desc: 'Array of indexed symbols' },
		{ pattern: /(?:get|scan)?Regions$/i, baseType: 'VLTRegionInfo[]', desc: 'Array of region descriptors' },
		{ pattern: /(?:get|find)?Lines$/i, baseType: 'string[]', desc: 'Array of text lines' }
	]);

	/**
	 * Infers array element return type from function name heuristics.
	 * [Pure Function] Complexity <= 3.
	 * @param {string} fnName
	 * @param {boolean} isAsync
	 * @returns {{ type: string; desc: string }}
	 * @private
	 */
	function _inferArrayReturn(fnName, isAsync) {
		for (const entry of _ARRAY_RETURN_PATTERNS) {
			if (entry.pattern.test(fnName)) {
				return { type: _wrapAsyncType(entry.baseType, isAsync), desc: entry.desc };
			}
		}
		return { type: _wrapAsyncType('unknown[]', isAsync), desc: 'Collection array of results' };
	}

	/**
	 * Rules table for expression-based primitive return inference.
	 * @type {ReadonlyArray<{ predicate: (e: string) => boolean; baseType: string; desc: string }>}
	 */
	const _EXPR_RETURN_RULES = Object.freeze([
		{ predicate: _isBooleanExpr, baseType: 'boolean', desc: 'True if operation succeeded, false otherwise' },
		{ predicate: _isStringExpr, baseType: 'string', desc: 'Synthesized or formatted string result' },
		{ predicate: _isNumberExpr, baseType: 'number', desc: 'Calculated numeric value' },
		{ predicate: _isObjectExpr, baseType: 'Record<string, unknown>', desc: 'Result object payload' }
	]);

	/**
	 * Infers return type from list of returned expressions.
	 * [Pure Function] Complexity <= 5.
	 * @param {string[]} expressions
	 * @param {boolean} isAsync
	 * @param {string} fnName
	 * @returns {{ type: string; desc: string }}
	 * @private
	 */
	function _inferTypeFromExpressions(expressions, isAsync, fnName) {
		if (expressions.every(_isArrayExpr)) {
			return _inferArrayReturn(fnName, isAsync);
		}
		for (const rule of _EXPR_RETURN_RULES) {
			if (expressions.every(rule.predicate)) {
				return { type: _wrapAsyncType(rule.baseType, isAsync), desc: rule.desc };
			}
		}

		const firstExpr = expressions[ 0 ];
		const dictMatch = DOMAIN_TYPE_DICTIONARY[ firstExpr ];
		if (dictMatch) {
			return { type: _wrapAsyncType(dictMatch.type, isAsync), desc: dictMatch.desc };
		}

		return { type: _wrapAsyncType('unknown', isAsync), desc: 'Resolved operation result' };
	}

	/**
	 * Infers function return type by inspecting its return statements and async keyword.
	 * [Pure Function] Complexity <= 4.
	 * @param {boolean} isAsync - True if function declared with async
	 * @param {string[]} bodyLines - Lines of function implementation
	 * @param {string} [fnName=''] - Optional function name for domain inference
	 * @returns {{ type: string; desc: string }}
	 * @private
	 */
	function _inferReturnType(isAsync, bodyLines, fnName = '') {
		const bodyText = bodyLines.join('\n');
		const returnMatches = [ ...bodyText.matchAll(/\breturn\b\s*([^;}\n]*)/g) ];

		if (returnMatches.length === 0) {
			const type = isAsync ? 'Promise<void>' : 'void';
			return { type, desc: isAsync ? 'Promise that resolves when async operations complete' : 'Does not return a value' };
		}

		const expressions = returnMatches
			.map(m => (m[ 1 ] || '').trim())
			.filter(expr => expr.length > 0 && expr !== 'undefined');

		if (expressions.length === 0) {
			const type = isAsync ? 'Promise<void>' : 'void';
			return { type, desc: isAsync ? 'Resolves when complete' : 'Early return' };
		}

		return _inferTypeFromExpressions(expressions, isAsync, fnName);
	}

	/**
	 * Canonical dictionary of function summary verb prefixes.
	 * @type {Record<string, string>}
	 */
	const _FUNCTION_SUMMARY_VERB_MAP = Object.freeze({
		get: 'Retrieves',
		set: 'Sets',
		init: 'Initializes',
		boot: 'Bootstraps and initializes',
		load: 'Loads and parses',
		save: 'Persists',
		render: 'Renders',
		build: 'Constructs',
		create: 'Creates a new',
		mount: 'Mounts',
		unmount: 'Unmounts and tears down',
		bind: 'Binds event listeners for',
		handle: 'Dispatches and handles',
		toggle: 'Toggles active state of',
		format: 'Formats and aligns',
		parse: 'Parses raw content into',
		scan: 'Scans and audits',
		verify: 'Validates integrity and contracts for',
		check: 'Checks status of',
		scaffold: 'Deterministically scaffolds',
		apply: 'Applies',
		reject: 'Reverts and rejects',
		update: 'Updates',
		select: 'Selects and focuses',
		has: 'Determines whether',
		is: 'Determines if'
	});

	/**
	 * Formats a summary verb into appropriate 3rd-person singular form.
	 * [Pure Helper] Complexity <= 3.
	 * @param {string} verb
	 * @returns {string}
	 * @private
	 */
	function _formatSummaryVerb(verb) {
		const mapped = _FUNCTION_SUMMARY_VERB_MAP[ verb ];
		if (mapped) return mapped;
		const capitalized = verb.charAt(0).toUpperCase() + verb.slice(1);
		if (/(?:s|sh|ch|x|z)$/.test(verb)) {
			return `${capitalized}es`;
		}
		return `${capitalized}s`;
	}

	/**
	 * Generates a clean human-readable verb-noun description for a function name.
	 * [Pure Function] Complexity <= 3.
	 * @param {string} fnName - Function name
	 * @returns {string}
	 * @private
	 */
	function _deriveFunctionSummary(fnName) {
		const clean = fnName.replace(/^_+/, '');
		const parts = clean.replace(/([A-Z])/g, ' $1').toLowerCase().trim().split(' ');
		const verb = parts[ 0 ];
		if (!verb) return `Executes ${clean}.`;

		const rest = parts.slice(1).join(' ');
		const formattedVerb = _formatSummaryVerb(verb);
		if (rest) {
			return `${formattedVerb} ${rest}.`;
		}
		return `${formattedVerb} target state.`;
	}

	/**
	 * Updates generic depth counter for union splitting.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} ch
	 * @param {number} depth
	 * @returns {number}
	 * @private
	 */
	function _updateGenericDepth(ch, depth) {
		if (ch === '<') return depth + 1;
		if (ch === '>') return Math.max(0, depth - 1);
		return depth;
	}

	/**
	 * Splits union string respecting nested angle brackets <>.
	 * [Pure Helper] Complexity <= 5.
	 * @param {string} typeStr
	 * @returns {string[]}
	 * @private
	 */
	function _splitUnionParts(typeStr) {
		const parts = [];
		let cur = '';
		let depth = 0;
		for (const ch of typeStr) {
			depth = _updateGenericDepth(ch, depth);
			const isDivider = ch === '|' && depth === 0;
			if (isDivider) {
				parts.push(cur.trim());
				cur = '';
			} else {
				cur += ch;
			}
		}
		if (cur.trim()) parts.push(cur.trim());
		return parts;
	}

	const _GENERIC_PRIMITIVE_TYPE_PATTERN = /^(?:string|number|boolean|void|null|undefined|unknown|any|object|Record|Map|Array|Promise)/;

	/**
	 * Tests if union member represents a specific sovereign DTO identifier.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} typePart
	 * @returns {boolean}
	 * @private
	 */
	function _isSovereignDTOMember(typePart) {
		return /^[A-Z]/.test(typePart) && !_GENERIC_PRIMITIVE_TYPE_PATTERN.test(typePart);
	}

	/**
	 * Extracts the primary (most specific) type from a TS union string.
	 * For example: `PhoenixProposalDTO | Record<string, unknown>` → `PhoenixProposalDTO`.
	 * If the primary type is a generic built-in, falls back to the full union.
	 * [Pure Function] Complexity <= 3.
	 * @param {string} typeStr
	 * @returns {string}
	 * @private
	 */
	function _primaryUnionType(typeStr) {
		if (!typeStr.includes(' | ')) return typeStr;
		const parts = _splitUnionParts(typeStr);
		const dtoMember = parts.find(_isSovereignDTOMember);
		return dtoMember || parts[ 0 ] || typeStr;
	}
	//#endregion [SEC-05]

	//#region [SEC-06] Contract Synthesis Engine & Strict JSDoc Block Formatter
	/**
	 * Resolves final return contract descriptor for a catalog entry.
	 * [Pure Helper] Complexity <= 4.
	 * @param {any} catalogEntry
	 * @param {string[]} bodyLines
	 * @param {boolean} isAsync
	 * @param {string} fnName
	 * @returns {{ type: string; desc: string }}
	 * @private
	 */
	function _resolveCatalogReturn(catalogEntry, bodyLines, isAsync, fnName) {
		const bodyReturn = bodyLines.length > 0 ? _inferReturnType(isAsync, bodyLines, fnName) : null;
		const PRIMITIVE_RETURNS = /^(?:boolean|string|number|void|Promise<boolean>|Promise<string>|Promise<number>|Promise<void>)$/;
		if (bodyReturn && PRIMITIVE_RETURNS.test(bodyReturn.type)) {
			return bodyReturn;
		}

		const catalogReturnType = isAsync && !catalogEntry.returnType.startsWith('Promise<')
			? `Promise<${catalogEntry.returnType}>`
			: catalogEntry.returnType;
		return { type: catalogReturnType, desc: isAsync ? 'Promise resolving with operation result' : 'Operation result' };
	}

	/**
	 * Builds a single parameter contract from catalog entry with fallback inference.
	 * [Pure Helper] Complexity <= 4.
	 * @param {{ name: string; defaultVal?: string }} rp
	 * @param {Map<string, any>} paramMap
	 * @param {string[]} bodyLines
	 * @returns {{ name: string; type: string; optional: boolean; defaultVal?: string; desc: string }}
	 * @private
	 */
	function _buildCatalogParam(rp, paramMap, bodyLines) {
		const matched = paramMap.get(rp.name);
		const rawType = matched?.type || DOMAIN_TYPE_DICTIONARY[ rp.name ]?.type || 'unknown';
		const resolvedType = _primaryUnionType(rawType);
		const finalType = resolvedType === 'unknown'
			? (_inferParamFromBody(rp.name, bodyLines) || 'unknown')
			: resolvedType;
		return {
			name: rp.name,
			type: finalType,
			optional: Boolean(rp.defaultVal || matched?.optional),
			defaultVal: rp.defaultVal,
			desc: matched?.desc || DOMAIN_TYPE_DICTIONARY[ rp.name ]?.desc || `Parameter ${rp.name}`
		};
	}

	/**
	 * Infers contract using ambient .d.ts method catalog entry.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} fnName
	 * @param {any} catalogEntry
	 * @param {Array<{ name: string; defaultVal?: string }>} rawParams
	 * @param {boolean} isAsync
	 * @param {string[]} bodyLines
	 * @returns {any}
	 * @private
	 */
	function _inferCatalogContract(fnName, catalogEntry, rawParams, isAsync, bodyLines) {
		const paramMap = new Map(catalogEntry.params.map((/** @type {{ name: any; }} */ p) => [ p.name, p ]));
		const mappedParams = rawParams.map(rp => _buildCatalogParam(rp, paramMap, bodyLines));
		const finalReturn = _resolveCatalogReturn(catalogEntry, bodyLines, isAsync, fnName);
		return {
			summary: catalogEntry.desc || _deriveFunctionSummary(fnName),
			params: mappedParams,
			returns: finalReturn
		};
	}

	/**
	 * Infers a single parameter descriptor using domain dictionary and body heuristics.
	 * [Pure Helper] Complexity <= 5.
	 * @param {{ name: string; defaultVal?: string }} rp
	 * @param {string[]} bodyLines
	 * @returns {{ name: string; type: string; optional: boolean; defaultVal?: string; desc: string }}
	 * @private
	 */
	function _inferHeuristicParam(rp, bodyLines) {
		const dictMatch = DOMAIN_TYPE_DICTIONARY[ rp.name ];
		if (dictMatch) {
			return {
				name: rp.name,
				type: dictMatch.type,
				optional: Boolean(rp.defaultVal),
				defaultVal: rp.defaultVal,
				desc: dictMatch.desc
			};
		}

		if (/^(?:is|has|should|can|enable)[A-Z]/.test(rp.name)) {
			return {
				name: rp.name,
				type: 'boolean',
				optional: Boolean(rp.defaultVal),
				defaultVal: rp.defaultVal,
				desc: `Flag indicating whether ${rp.name.slice(2).toLowerCase()} is enabled`
			};
		}

		const bodyType = _inferParamFromBody(rp.name, bodyLines);
		if (bodyType) {
			return {
				name: rp.name,
				type: bodyType,
				optional: Boolean(rp.defaultVal),
				defaultVal: rp.defaultVal,
				desc: `Input ${rp.name}`
			};
		}

		return {
			name: rp.name,
			type: 'unknown',
			optional: Boolean(rp.defaultVal),
			defaultVal: rp.defaultVal,
			desc: `Input parameter ${rp.name}`
		};
	}

	/**
	 * Infers contract using heuristic analysis across parameters and function body.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} fnName
	 * @param {Array<{ name: string; defaultVal?: string }>} rawParams
	 * @param {boolean} isAsync
	 * @param {string[]} bodyLines
	 * @returns {any}
	 * @private
	 */
	function _inferHeuristicContract(fnName, rawParams, isAsync, bodyLines) {
		const inferredParams = rawParams.map(rp => _inferHeuristicParam(rp, bodyLines));
		const returns = _inferReturnType(isAsync, bodyLines, fnName);
		return {
			summary: _deriveFunctionSummary(fnName),
			params: inferredParams,
			returns
		};
	}

	/**
	 * Infers the complete typed contract for a function.
	 * [Pure Function] Complexity <= 2.
	 * @param {string} fnName - Function identifier
	 * @param {Array<{ name: string; defaultVal?: string }>} rawParams - Extracted parameters
	 * @param {boolean} [isAsync=false] - True if async function
	 * @param {string[]} [bodyLines=[]] - Function body implementation lines for static analysis
	 * @returns {{
	 *   summary: string;
	 *   params: Array<{ name: string; type: string; optional: boolean; defaultVal?: string; desc: string }>;
	 *   returns: { type: string; desc: string };
	 * }}
	 */
	function inferContract(fnName, rawParams, isAsync = false, bodyLines = []) {
		const catalogEntry = _methodCatalog.get(fnName);
		if (catalogEntry) {
			return _inferCatalogContract(fnName, catalogEntry, rawParams, isAsync, bodyLines);
		}
		return _inferHeuristicContract(fnName, rawParams, isAsync, bodyLines);
	}

	/**
	 * Formats a single @param tag entry with optional default value expression.
	 * [Pure Function] Complexity <= 3.
	 * @param {{ name: string; type: string; optional: boolean; defaultVal?: string; desc: string }} p
	 * @returns {string}
	 * @private
	 */
	function _formatParamDocTag(p) {
		let paramExpr = p.name;
		if (p.optional && p.defaultVal) {
			paramExpr = `[${p.name}=${p.defaultVal}]`;
		} else if (p.optional) {
			paramExpr = `[${p.name}]`;
		}
		const descSuffix = p.desc ? ` - ${p.desc}` : '';
		return `@param {${p.type}} ${paramExpr}${descSuffix}`;
	}

	/**
	 * Formats an inferred contract into standard JSDoc comment lines.
	 * [Pure Function] Complexity <= 4.
	 * @param {{
	 *   summary: string;
	 *   params: Array<{ name: string; type: string; optional: boolean; defaultVal?: string; desc: string }>;
	 *   returns: { type: string; desc: string };
	 * }} contract - Inferred function contract
	 * @param {string} [indent] - Leading indentation string
	 * @returns {string} Clean multi-line JSDoc comment string
	 */
	function formatJSDoc(contract, indent = '') {
		const lines = [
			`${indent}/**`,
			`${indent} * ${contract.summary}`
		];

		if (contract.params.length > 0) {
			for (const p of contract.params) {
				lines.push(`${indent} * ${_formatParamDocTag(p)}`);
			}
		}

		if (contract.returns) {
			const returnSuffix = contract.returns.desc ? ` - ${contract.returns.desc}` : '';
			lines.push(`${indent} * @returns {${contract.returns.type}}${returnSuffix}`);
		}

		lines.push(`${indent} */`);
		return lines.join('\n');
	}
	//#endregion [SEC-06]

	//#region [SEC-07] Document AST Line Scaffolder, Catalog Loader & Sovereign Membrane
	/**
	 * Extracts leading indentation whitespace from a line.
	 * [Pure Helper] Complexity <= 2.
	 * @param {string} lineText
	 * @returns {string}
	 * @private
	 */
	function _extractLineIndentation(lineText) {
		const indentMatch = /^\s*/.exec(lineText);
		return indentMatch ? indentMatch[ 0 ] : '';
	}

	/**
	 * Matches function or method declaration syntax on a single line.
	 * [Pure Helper] Complexity <= 4.
	 * @param {string} lineText
	 * @returns {{ isAsync: boolean; fnName: string; rawParamStr: string } | null}
	 * @private
	 */
	function _matchFnDeclaration(lineText) {
		const fnDeclarationRegex = /(?:(async)\s+)?function\s+([A-Za-z0-9_$]+)\s*\(([^)]*)\)/;
		const arrowFnRegex = /(?:const|let|var)\s+([A-Za-z0-9_$]+)\s*=\s*(?:(async)\s*)?\(([^)]*)\)\s*=>/;
		const methodFnRegex = /^\s*(?:(async)\s+)?([A-Za-z0-9_$]+)\s*\(([^)]*)\)\s*\x7B/;

		const match = fnDeclarationRegex.exec(lineText) ||
			arrowFnRegex.exec(lineText) ||
			methodFnRegex.exec(lineText);

		if (!match) return null;
		return {
			isAsync: Boolean(match[ 1 ]),
			fnName: match[ 2 ] || 'anonymous',
			rawParamStr: match[ 3 ] || ''
		};
	}

	/**
	 * Parses a single raw parameter token into name and optional default value.
	 * [Pure Helper] Complexity <= 3.
	 * @param {string} rawEntry
	 * @returns {{ name: string; defaultVal?: string } | null}
	 * @private
	 */
	function _parseRawParamEntry(rawEntry) {
		const trimmed = rawEntry.trim();
		if (!trimmed) return null;
		const parts = trimmed.split('=');
		const name = (parts[ 0 ] || '').trim();
		if (!name) return null;
		const defaultVal = parts[ 1 ] ? parts[ 1 ].trim() : undefined;
		return { name, defaultVal };
	}

	/**
	 * Parses raw parameter list string into structured parameter objects.
	 * [Pure Helper] Complexity <= 3.
	 * @param {string} rawParamStr
	 * @returns {Array<{ name: string; defaultVal?: string }>}
	 * @private
	 */
	function _parseRawSignatureParams(rawParamStr) {
		if (!rawParamStr) return [];
		const entries = rawParamStr.split(',');
		const parsed = [];
		for (const entry of entries) {
			const item = _parseRawParamEntry(entry);
			if (item) parsed.push(item);
		}
		return parsed;
	}

	/**
	 * Determines the line index and deletion count for contract insertion or replacement.
	 * [Pure Helper] Complexity <= 5.
	 * @param {string[]} lines
	 * @param {number} targetIndex
	 * @param {boolean} [overwrite=false]
	 * @returns {{ insertIndex: number; replaceCount: number; valid: boolean }}
	 * @private
	 */
	function _resolveDocReplacementRange(lines, targetIndex, overwrite = false) {
		const prevLine = lines[ targetIndex - 1 ] || '';
		if (!prevLine.trim().endsWith('*/')) {
			return { insertIndex: targetIndex, replaceCount: 0, valid: true };
		}
		if (!overwrite) {
			return { insertIndex: targetIndex, replaceCount: 0, valid: false };
		}
		let startDocIdx = targetIndex - 1;
		while (startDocIdx >= 0 && !lines[ startDocIdx ].trim().startsWith('/**')) {
			startDocIdx--;
		}
		if (startDocIdx < 0) {
			return { insertIndex: targetIndex, replaceCount: 0, valid: false };
		}
		return { insertIndex: startDocIdx, replaceCount: targetIndex - startDocIdx, valid: true };
	}

	/**
	 * Scaffolds an accurate, strict JSDoc contract above a JavaScript function.
	 * [Pure Function] Complexity <= 6.
	 * @param {string} fullSource - Entire document source text
	 * @param {number} lineNum - 1-indexed target function line number
	 * @param {{ overwrite?: boolean }} [options] - Optional scaffold options
	 * @returns {{ scaffoldedSource: string; jsdocBlock: string; insertedLineCount: number } | null}
	 */
	function scaffoldContractAtLine(fullSource, lineNum, options = {}) {
		if (!fullSource || lineNum <= 0) return null;
		const lines = fullSource.split('\n');
		const targetIndex = lineNum - 1;
		if (targetIndex >= lines.length) return null;

		const range = _resolveDocReplacementRange(lines, targetIndex, Boolean(options.overwrite));
		if (!range.valid) {
			return null;
		}

		const lineText = lines[ targetIndex ] || '';
		const fnMatch = _matchFnDeclaration(lineText);
		if (!fnMatch) return null;

		const rawParams = _parseRawSignatureParams(fnMatch.rawParamStr);
		const bodyLines = lines.slice(targetIndex + 1, targetIndex + 80);
		const contract = inferContract(fnMatch.fnName, rawParams, fnMatch.isAsync, bodyLines);
		const indent = _extractLineIndentation(lineText);
		const jsdocBlock = formatJSDoc(contract, indent);

		lines.splice(range.insertIndex, range.replaceCount, jsdocBlock);

		return {
			scaffoldedSource: lines.join('\n'),
			jsdocBlock,
			insertedLineCount: jsdocBlock.split('\n').length
		};
	}

	/**
	 * Determines if a line is an un-annotated function declaration.
	 * [Pure Helper] Complexity <= 4.
	 * @param {string[]} lines
	 * @param {number} index
	 * @returns {boolean}
	 * @private
	 */
	function _isUnannotatedFnLine(lines, index) {
		const line = lines[ index ];
		const isFn = /(?:async\s+)?function\s+[A-Za-z0-9_$]+\s*\(/.test(line) ||
			/(?:const|let|var)\s+[A-Za-z0-9_$]+\s*=\s*(?:async\s*)?\([^)]*\)\s*=>/.test(line);
		if (!isFn) return false;
		const prevLine = lines[ index - 1 ] || '';
		return !prevLine.trim().endsWith('*/');
	}

	/**
	 * Scaffolds strict JSDoc contracts above all un-annotated functions in a document.
	 * [Pure Function] Complexity <= 4.
	 * @param {string} fullSource - Entire document source text
	 * @returns {{ scaffoldedSource: string; annotatedCount: number }}
	 */
	function scaffoldAllContracts(fullSource) {
		if (!fullSource) return { scaffoldedSource: '', annotatedCount: 0 };
		const lines = fullSource.split('\n');
		let annotatedCount = 0;

		for (let i = lines.length - 1; i >= 0; i--) {
			if (_isUnannotatedFnLine(lines, i)) {
				const res = scaffoldContractAtLine(lines.join('\n'), i + 1);
				if (res) {
					lines.splice(i, 0, res.jsdocBlock);
					annotatedCount++;
				}
			}
		}

		return {
			scaffoldedSource: lines.join('\n'),
			annotatedCount
		};
	}

	/**
	 * Attempts loading declarations from Node.js filesystem paths.
	 * [Pure Function] Complexity <= 7.
	 * @returns {number}
	 * @private
	 */
	function _loadCatalogFromNodeFs() {
		if (typeof require === 'undefined' || typeof process === 'undefined') return 0;
		try {
			const fs = require('node:fs');
			const path = require('node:path');
			const candidates = [
				path.resolve(__dirname, 'phoenix.d.ts'),
				path.resolve(__dirname, '../phoenix/phoenix.d.ts'),
				path.resolve(process.cwd(), 'phoenix/phoenix.d.ts')
			];
			for (const candidatePath of candidates) {
				if (fs.existsSync(candidatePath)) {
					const content = fs.readFileSync(candidatePath, 'utf8');
					return ingestDeclarations(content);
				}
			}
		} catch {
			// Fall through to browser strategy if Node fs is unavailable
		}
		return 0;
	}

	/**
	 * Loads .d.ts from virtual filesystem if present.
	 * [Pure Helper] Complexity <= 4.
	 * @returns {number}
	 * @private
	 */
	function _loadCatalogFromVfs() {
		const vfs = /** @type {{ get(k: string): string | undefined } | undefined} */ (global._vfs);
		if (!vfs || typeof vfs.get !== 'function') return 0;
		const dts = vfs.get('phoenix/phoenix.d.ts') || vfs.get('phoenix.d.ts');
		if (dts) {
			return ingestDeclarations(dts);
		}
		return 0;
	}

	/**
	 * Fetches .d.ts from network endpoint in browser environments.
	 * [State-Mutating Helper] Complexity <= 4.
	 * @returns {Promise<number>}
	 * @private
	 */
	async function _fetchCatalogFromNetwork() {
		if (typeof fetch !== 'function') return 0;
		try {
			const res = await fetch('phoenix.d.ts');
			if (!res.ok) return 0;
			const text = await res.text();
			return ingestDeclarations(text);
		} catch {
			// Network fetch failed or running offline over file:///; fallback to domain dictionary
			return 0;
		}
	}

	/**
	 * Attempts loading declarations from browser VFS or network fetch.
	 * [State-Mutating] Complexity <= 3.
	 * @returns {Promise<number>}
	 * @private
	 */
	async function _loadCatalogFromBrowser() {
		if (typeof window === 'undefined') return 0;

		const vfsCount = _loadCatalogFromVfs();
		if (vfsCount > 0) return vfsCount;

		return _fetchCatalogFromNetwork();
	}

	/**
	 * Initializes the type catalog from phoenix.d.ts if running in browser or Node environment.
	 * [Pure Function] Complexity <= 3.
	 * @returns {Promise<number>}
	 */
	async function initializeTypeCatalog() {
		if (_catalogInitialized) return _methodCatalog.size;

		const nodeCount = _loadCatalogFromNodeFs();
		if (nodeCount > 0) return nodeCount;

		return _loadCatalogFromBrowser();
	}

	const PhoenixTypeResolver = Object.freeze({
		ingestDeclarations,
		initializeTypeCatalog,
		inferContract,
		formatJSDoc,
		scaffoldContractAtLine,
		scaffoldAllContracts,
		isInitialized: () => _catalogInitialized,
		getMethodCount: () => _methodCatalog.size,
		getInterfaceCount: () => _interfaceCatalog.size,
		getDomainType: (/** @type {string | number} */ token) => DOMAIN_TYPE_DICTIONARY[ token ] || null,
		getMethodDefinition: (/** @type {string} */ token) => _methodCatalog.get(token) || null,
		getInterfaceDefinition: (/** @type {string} */ token) => _interfaceCatalog.get(token) || null
	});

	global.PhoenixTypeResolver = PhoenixTypeResolver;
	if (typeof module !== 'undefined' && module.exports) {
		module.exports = PhoenixTypeResolver;
	}

	// Auto-trigger background ingestion
	if (typeof setTimeout === 'function') {
		setTimeout(() => {
			initializeTypeCatalog().catch(() => {
				// Non-fatal background type catalog ingestion error
			});
		}, 0);
	}
	//#endregion [SEC-07]
})(
	(() => {
		if (typeof globalThis !== 'undefined') return globalThis;
		if (typeof window !== 'undefined') return window;
		if (typeof global !== 'undefined') return global;
		return {};
	})()
);
