/**
 * ============================================================================
 * EMBERLIGHT SOVEREIGN ENGINE: MANIFEST PROGRESSION SUB-MODULE
 * Document Identifier: VSRP-001-MANIFEST-PROGRESSION
 * Authority: Host SSOT Staging Membrane
 * ============================================================================
 */
if (typeof window !== 'undefined') window._ManifestInternal = window._ManifestInternal || {};

(() => {
	'use strict';

	const AetherEssences = {
		IRON: {
			id: 'IRON',
			label: 'Path of Iron',
			element: 'PHYSICAL',
			role: 'Vanguard / Bulwark',
		},
		EMBER: {
			id: 'EMBER',
			label: 'Path of Ember',
			element: 'FIRE',
			role: 'Combustion / Strike',
		},
		TIDE: {
			id: 'TIDE',
			label: 'Path of Tide',
			element: 'ICE',
			role: 'Time / Crystallization',
		},
		LUMEN: {
			id: 'LUMEN',
			label: 'Path of Lumen',
			element: 'HOLY',
			role: 'Restoration / Wards',
		},
		UMBRA: {
			id: 'UMBRA',
			label: 'Path of Umbra',
			element: 'POISON',
			role: 'Affliction / Skirmish',
		},
	};

	const AetherNodes = {
		// === IRON ESSENCE NODES ===
		iron_root: {
			id: 'iron_root',
			essence: 'IRON',
			label: 'Bulwark Discipline',
			desc: '+8 Max HP, +2 DEF',
			type: 'attribute',
			isRoot: true,
			statDeltas: { hp: 8, def: 2 },
			neighbors: ['iron_cleave', 'iron_guard_1', 'iron_hp_1'],
			spCost: 1,
			capabilityTag: null,
		},
		iron_cleave: {
			id: 'iron_cleave',
			essence: 'IRON',
			label: 'Heavy Cleave',
			desc: 'Brutal frontline strike (1.4x ATK)',
			type: 'active',
			element: 'PHYSICAL',
			subType: 'strike',
			targetType: 'enemy',
			mult: 1.4,
			mpCost: 0,
			neighbors: ['iron_root', 'iron_sunder', 'ember_bridge_1'],
			spCost: 1,
			capabilityTag: null,
		},
		iron_guard_1: {
			id: 'iron_guard_1',
			essence: 'IRON',
			label: 'Vanguard Aegis',
			desc: 'Frontline body-blocks single-target strikes aimed at backline',
			type: 'keystone',
			statDeltas: { def: 2 },
			neighbors: ['iron_root', 'lumen_bridge_1', 'iron_def_1'],
			spCost: 2,
			capabilityTag: null,
		},
		iron_hp_1: {
			id: 'iron_hp_1',
			essence: 'IRON',
			label: 'Iron Flesh',
			desc: '+12 Max HP',
			type: 'attribute',
			statDeltas: { hp: 12 },
			neighbors: ['iron_root', 'iron_def_1'],
			spCost: 1,
			capabilityTag: null,
		},
		iron_def_1: {
			id: 'iron_def_1',
			essence: 'IRON',
			label: 'Fortified Posture',
			desc: '+3 DEF, +4 Max HP',
			type: 'attribute',
			statDeltas: { def: 3, hp: 4 },
			neighbors: ['iron_guard_1', 'iron_hp_1', 'iron_sunder'],
			spCost: 1,
			capabilityTag: null,
		},
		iron_sunder: {
			id: 'iron_sunder',
			essence: 'IRON',
			label: 'Armor Sunder',
			desc: 'Crushing blow that pierces defense (1.7x ATK)',
			type: 'active',
			element: 'PHYSICAL',
			subType: 'strike',
			targetType: 'enemy',
			mult: 1.7,
			mpCost: 1,
			neighbors: ['iron_cleave', 'iron_def_1', 'iron_bru_3'],
			spCost: 2,
			capabilityTag: null,
		},
		iron_bru_3: {
			id: 'iron_bru_3',
			essence: 'IRON',
			label: 'Juggernaut Impact',
			desc: 'Cataclysmic melee execution (2.2x ATK)',
			type: 'active',
			element: 'PHYSICAL',
			subType: 'strike',
			targetType: 'enemy',
			mult: 2.2,
			mpCost: 3,
			resonance: true,
			tier: 3,
			neighbors: ['iron_sunder'],
			spCost: 3,
			capabilityTag: null,
		},

		// === EMBER ESSENCE NODES ===
		ember_root: {
			id: 'ember_root',
			essence: 'EMBER',
			label: 'Spark Attunement',
			desc: '+3 ATK, +6 Max MP',
			type: 'attribute',
			isRoot: true,
			statDeltas: { atk: 3, mp: 6 },
			neighbors: ['ember_bolt_1', 'ember_burn_1', 'ember_crit_1'],
			spCost: 1,
			capabilityTag: 'cap:elemental.scorch',
		},
		ember_bolt_1: {
			id: 'ember_bolt_1',
			essence: 'EMBER',
			label: 'Flame Spark',
			desc: 'Direct fire projectile (Power 10)',
			type: 'active',
			element: 'FIRE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 10,
			mpCost: 3,
			neighbors: ['ember_root', 'ember_bridge_1', 'ember_burst'],
			spCost: 1,
			capabilityTag: 'cap:elemental.scorch',
		},
		ember_burn_1: {
			id: 'ember_burn_1',
			essence: 'EMBER',
			label: 'Thermal Surge',
			desc: '+2 ATK, +1 AGI',
			type: 'attribute',
			statDeltas: { atk: 2, agi: 1 },
			neighbors: ['ember_root', 'ember_catalyst'],
			spCost: 1,
			capabilityTag: null,
		},
		ember_crit_1: {
			id: 'ember_crit_1',
			essence: 'EMBER',
			label: 'Incendiary Focus',
			desc: '+6 Max MP, +2 ATK',
			type: 'attribute',
			statDeltas: { mp: 6, atk: 2 },
			neighbors: ['ember_root', 'ember_burst'],
			spCost: 1,
			capabilityTag: null,
		},
		ember_burst: {
			id: 'ember_burst',
			essence: 'EMBER',
			label: 'Inferno Orb',
			desc: 'High-heat thermal blast (Power 18)',
			type: 'active',
			element: 'FIRE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 18,
			mpCost: 6,
			resonance: true,
			neighbors: ['ember_bolt_1', 'ember_crit_1', 'ember_des_3'],
			spCost: 2,
			capabilityTag: 'cap:elemental.scorch',
		},
		ember_catalyst: {
			id: 'ember_catalyst',
			essence: 'EMBER',
			label: 'Thermal Catalyst',
			desc: 'Fire strikes against frozen or burning targets gain +50% DMG',
			type: 'keystone',
			statDeltas: { atk: 3 },
			neighbors: ['ember_burn_1', 'tide_bridge_1'],
			spCost: 2,
			capabilityTag: 'cap:elemental.scorch',
		},
		ember_des_3: {
			id: 'ember_des_3',
			essence: 'EMBER',
			label: 'Hellfire Conflagration',
			desc: 'Signature pyroclastic devastation (Power 26)',
			type: 'active',
			element: 'FIRE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 26,
			mpCost: 10,
			resonance: true,
			tier: 3,
			neighbors: ['ember_burst'],
			spCost: 3,
			capabilityTag: 'cap:elemental.scorch',
		},

		// === TIDE ESSENCE NODES ===
		tide_root: {
			id: 'tide_root',
			essence: 'TIDE',
			label: 'Flow Attunement',
			desc: '+2 AGI, +8 Max MP',
			type: 'attribute',
			isRoot: true,
			statDeltas: { agi: 2, mp: 8 },
			neighbors: ['tide_frost_1', 'tide_haste_1', 'tide_def_1'],
			spCost: 1,
			capabilityTag: 'cap:elemental.freeze',
		},
		tide_frost_1: {
			id: 'tide_frost_1',
			essence: 'TIDE',
			label: 'Frost Spike',
			desc: 'Piercing ice crystallization (Power 12)',
			type: 'active',
			element: 'ICE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 12,
			mpCost: 4,
			neighbors: ['tide_root', 'tide_bridge_1', 'tide_blizzard'],
			spCost: 1,
			capabilityTag: 'cap:elemental.freeze',
		},
		tide_haste_1: {
			id: 'tide_haste_1',
			essence: 'TIDE',
			label: 'Quickstep Surge',
			desc: '+2 AGI, +6 Max HP',
			type: 'attribute',
			statDeltas: { agi: 2, hp: 6 },
			neighbors: ['tide_root', 'tide_chronos'],
			spCost: 1,
			capabilityTag: null,
		},
		tide_def_1: {
			id: 'tide_def_1',
			essence: 'TIDE',
			label: 'Glacial Shell',
			desc: '+2 DEF, +6 Max MP',
			type: 'attribute',
			statDeltas: { def: 2, mp: 6 },
			neighbors: ['tide_root', 'umbra_bridge_1'],
			spCost: 1,
			capabilityTag: null,
		},
		tide_blizzard: {
			id: 'tide_blizzard',
			essence: 'TIDE',
			label: 'Glacial Nova',
			desc: 'Sub-zero freezing blast (Power 20)',
			type: 'active',
			element: 'ICE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 20,
			mpCost: 7,
			resonance: true,
			neighbors: ['tide_frost_1', 'tide_freeze_3'],
			spCost: 2,
			capabilityTag: 'cap:elemental.freeze',
		},
		tide_chronos: {
			id: 'tide_chronos',
			essence: 'TIDE',
			label: 'Temporal Velocity',
			desc: 'Reduces action CTB delay by 15% and grants +2 AGI',
			type: 'keystone',
			statDeltas: { agi: 2 },
			neighbors: ['tide_haste_1'],
			spCost: 2,
			capabilityTag: null,
		},
		tide_freeze_3: {
			id: 'tide_freeze_3',
			essence: 'TIDE',
			label: 'Absolute Zero',
			desc: 'Complete thermal cessation blast (Power 28)',
			type: 'active',
			element: 'ICE',
			subType: 'bolt',
			targetType: 'enemy',
			power: 28,
			mpCost: 12,
			resonance: true,
			tier: 3,
			neighbors: ['tide_blizzard'],
			spCost: 3,
			capabilityTag: 'cap:elemental.freeze',
		},

		// === LUMEN ESSENCE NODES ===
		lumen_root: {
			id: 'lumen_root',
			essence: 'LUMEN',
			label: 'Radiant Dawn',
			desc: '+8 Max HP, +8 Max MP',
			type: 'attribute',
			isRoot: true,
			statDeltas: { hp: 8, mp: 8 },
			neighbors: ['lumen_heal_1', 'lumen_smite_1', 'lumen_ward_1'],
			spCost: 1,
			capabilityTag: 'cap:sanctuary.consecrate',
		},
		lumen_heal_1: {
			id: 'lumen_heal_1',
			essence: 'LUMEN',
			label: 'Purifying Light',
			desc: 'Holy recovery incantation (Power 14)',
			type: 'active',
			element: 'HOLY',
			subType: 'heal',
			targetType: 'ally',
			power: 14,
			mpCost: 3,
			neighbors: ['lumen_root', 'lumen_bridge_1', 'lumen_sanctuary'],
			spCost: 1,
			capabilityTag: 'cap:sanctuary.consecrate',
		},
		lumen_smite_1: {
			id: 'lumen_smite_1',
			essence: 'LUMEN',
			label: 'Holy Smite',
			desc: 'Radiant smiting beam (Power 12)',
			type: 'active',
			element: 'HOLY',
			subType: 'bolt',
			targetType: 'enemy',
			power: 12,
			mpCost: 4,
			neighbors: ['lumen_root', 'lumen_judg_3'],
			spCost: 1,
			capabilityTag: null,
		},
		lumen_ward_1: {
			id: 'lumen_ward_1',
			essence: 'LUMEN',
			label: 'Aegis Ward',
			desc: '+2 DEF, +1 ATK',
			type: 'attribute',
			statDeltas: { def: 2, atk: 1 },
			neighbors: ['lumen_root', 'lumen_res_3'],
			spCost: 1,
			capabilityTag: null,
		},
		lumen_sanctuary: {
			id: 'lumen_sanctuary',
			essence: 'LUMEN',
			label: 'Greater Sanctuary',
			desc: 'Mass radiant restoration (Power 24)',
			type: 'active',
			element: 'HOLY',
			subType: 'heal',
			targetType: 'ally',
			power: 24,
			mpCost: 7,
			resonance: true,
			neighbors: ['lumen_heal_1', 'lumen_res_3'],
			spCost: 2,
			capabilityTag: 'cap:sanctuary.consecrate',
		},
		lumen_res_3: {
			id: 'lumen_res_3',
			essence: 'LUMEN',
			label: 'Divine Grace',
			desc: 'Healing potency +25% and purges poison/burn on target',
			type: 'keystone',
			statDeltas: { def: 2, mp: 6 },
			neighbors: ['lumen_ward_1', 'lumen_sanctuary'],
			spCost: 2,
			capabilityTag: 'cap:sanctuary.consecrate',
		},
		lumen_judg_3: {
			id: 'lumen_judg_3',
			essence: 'LUMEN',
			label: 'Pillar of Judgment',
			desc: 'Heavenly smiting blast (Power 28)',
			type: 'active',
			element: 'HOLY',
			subType: 'bolt',
			targetType: 'enemy',
			power: 28,
			mpCost: 12,
			resonance: true,
			tier: 3,
			neighbors: ['lumen_smite_1'],
			spCost: 3,
			capabilityTag: null,
		},

		// === UMBRA ESSENCE NODES ===
		umbra_root: {
			id: 'umbra_root',
			essence: 'UMBRA',
			label: 'Shadow Discipline',
			desc: '+2 ATK, +2 AGI, +4 Max MP',
			type: 'attribute',
			isRoot: true,
			statDeltas: { atk: 2, agi: 2, mp: 4 },
			neighbors: ['umbra_strike_1', 'umbra_toxin_1', 'umbra_gale_1'],
			spCost: 1,
			capabilityTag: 'cap:elemental.dispel',
		},
		umbra_strike_1: {
			id: 'umbra_strike_1',
			essence: 'UMBRA',
			label: 'Shadow Pierce',
			desc: 'Precision skirmish strike (1.5x ATK)',
			type: 'active',
			element: 'PHYSICAL',
			subType: 'strike',
			targetType: 'enemy',
			mult: 1.5,
			mpCost: 1,
			neighbors: ['umbra_root', 'umbra_bridge_1', 'umbra_assassinate'],
			spCost: 1,
			capabilityTag: null,
		},
		umbra_toxin_1: {
			id: 'umbra_toxin_1',
			essence: 'UMBRA',
			label: 'Blight Touch',
			desc: '+2 ATK, +6 Max MP',
			type: 'attribute',
			statDeltas: { atk: 2, mp: 6 },
			neighbors: ['umbra_root', 'umbra_dispel'],
			spCost: 1,
			capabilityTag: null,
		},
		umbra_gale_1: {
			id: 'umbra_gale_1',
			essence: 'UMBRA',
			label: 'Wind Cloak',
			desc: '+2 AGI, +2 DEF',
			type: 'attribute',
			statDeltas: { agi: 2, def: 2 },
			neighbors: ['umbra_root', 'umbra_dispel'],
			spCost: 1,
			capabilityTag: 'cap:elemental.dispel',
		},
		umbra_dispel: {
			id: 'umbra_dispel',
			essence: 'UMBRA',
			label: 'Shadow Gale',
			desc: 'Dispersing miasma gust (Power 14)',
			type: 'active',
			element: 'POISON',
			subType: 'bolt',
			targetType: 'enemy',
			power: 14,
			mpCost: 4,
			neighbors: ['umbra_toxin_1', 'umbra_gale_1', 'umbra_assassinate'],
			spCost: 2,
			capabilityTag: 'cap:elemental.dispel',
		},
		umbra_assassinate: {
			id: 'umbra_assassinate',
			essence: 'UMBRA',
			label: 'Death Mark',
			desc: 'Lethal shadow assassination (2.4x ATK)',
			type: 'active',
			element: 'PHYSICAL',
			subType: 'strike',
			targetType: 'enemy',
			mult: 2.4,
			mpCost: 4,
			resonance: true,
			tier: 3,
			neighbors: ['umbra_strike_1', 'umbra_dispel'],
			spCost: 3,
			capabilityTag: null,
		},

		// === CROSS-DISCIPLINE BRIDGES (HYBRIDS) ===
		ember_bridge_1: {
			id: 'ember_bridge_1',
			essence: 'EMBER',
			label: 'Molten Edge',
			desc: 'Ignited physical blade strike (1.8x ATK)',
			type: 'active',
			element: 'FIRE',
			subType: 'strike',
			targetType: 'enemy',
			mult: 1.8,
			mpCost: 3,
			neighbors: ['iron_cleave', 'ember_bolt_1'],
			spCost: 2,
			capabilityTag: 'cap:elemental.scorch',
		},
		lumen_bridge_1: {
			id: 'lumen_bridge_1',
			essence: 'LUMEN',
			label: 'Vanguard Beacon',
			desc: 'Protective healing surge (Power 12)',
			type: 'active',
			element: 'HOLY',
			subType: 'heal',
			targetType: 'ally',
			power: 12,
			mpCost: 4,
			neighbors: ['iron_guard_1', 'lumen_heal_1'],
			spCost: 2,
			capabilityTag: 'cap:sanctuary.consecrate',
		},
		tide_bridge_1: {
			id: 'tide_bridge_1',
			essence: 'TIDE',
			label: 'Thermal Shock Catalyst',
			desc: 'Combines Ice and Fire disciplines for +35% elemental reaction DMG',
			type: 'keystone',
			statDeltas: { atk: 2, agi: 1 },
			neighbors: ['ember_catalyst', 'tide_frost_1'],
			spCost: 2,
			capabilityTag: 'cap:elemental.freeze',
		},
		umbra_bridge_1: {
			id: 'umbra_bridge_1',
			essence: 'UMBRA',
			label: 'Mist Walker',
			desc: 'Evasion +15% and complete immunity to toxic miasma',
			type: 'keystone',
			statDeltas: { agi: 2, def: 1 },
			neighbors: ['tide_def_1', 'umbra_strike_1'],
			spCost: 2,
			capabilityTag: 'cap:elemental.dispel',
		},
	};

	const SkillTrees = {
		HERO: {
			RESOLVE: [
				{
					id: 'hero_res_1',
					tier: 1,
					label: 'Iron Will',
					desc: '+4 Max HP',
					type: 'passive',
					statDeltas: { hp: 4 },
				},
				{
					id: 'hero_res_2',
					tier: 2,
					label: 'Steadfast',
					desc: '+2 DEF',
					type: 'passive',
					statDeltas: { def: 2 },
				},
				{
					id: 'hero_res_3',
					tier: 3,
					label: 'Unbroken',
					desc: '+2 AGI',
					type: 'passive',
					statDeltas: { agi: 2 },
				},
			],
			BLADE_ARTS: [
				{
					id: 'hero_bla_1',
					tier: 1,
					label: 'Power Strike',
					desc: 'Heavy strike',
					type: 'active',
					element: 'PHYSICAL',
					targetType: 'enemy',
					mpCost: 0,
					mult: 1.3,
					subType: 'strike',
				},
				{
					id: 'hero_bla_2',
					tier: 2,
					label: 'Piercing Drag',
					desc: 'Pull backline foe into vanguard',
					type: 'active',
					element: 'PHYSICAL',
					targetType: 'enemy',
					mpCost: 3,
					mult: 1.6,
					displacement: 'PULL',
					subType: 'strike',
				},
				{
					id: 'hero_bla_3',
					tier: 3,
					label: 'Ember Finisher',
					desc: 'Signature hit',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 2,
					mult: 2.1,
					subType: 'strike',
					resonance: true,
				},
			],
			LIGHT_FRAGMENTS: [
				{
					id: 'hero_lig_1',
					tier: 1,
					label: 'Minor Light',
					desc: 'Small heal',
					type: 'active',
					element: 'HOLY',
					targetType: 'ally',
					mpCost: 2,
					power: 6,
					subType: 'heal',
					resonance: true,
				},
				{
					id: 'hero_lig_2',
					tier: 2,
					label: 'Warding Glow',
					desc: '+1 DEF',
					type: 'passive',
					statDeltas: { def: 1 },
					resonance: true,
				},
				{
					id: 'hero_lig_3',
					tier: 3,
					label: 'Ember Beam',
					desc: 'Magic damage',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 4,
					power: 14,
					subType: 'bolt',
					resonance: true,
				},
			],
		},
		WARRIOR: {
			TACTICAL_DEFENSE: [
				{
					id: 'war_tac_1',
					tier: 1,
					label: 'Bulwark',
					desc: '+6 Max HP',
					type: 'passive',
					statDeltas: { hp: 6 },
				},
				{
					id: 'war_tac_2',
					tier: 2,
					label: 'Guard Stance',
					desc: '+3 DEF',
					type: 'passive',
					statDeltas: { def: 3 },
				},
				{
					id: 'war_tac_3',
					tier: 3,
					label: 'Battle Instinct',
					desc: '+1 AGI',
					type: 'passive',
					statDeltas: { agi: 1 },
				},
			],
			WAR_CRY: [
				{
					id: 'war_cry_1',
					tier: 1,
					label: 'Challenge',
					desc: '+2 ATK',
					type: 'passive',
					statDeltas: { atk: 2 },
				},
				{
					id: 'war_cry_2',
					tier: 2,
					label: 'Rallying Roar',
					desc: '+4 Max HP',
					type: 'passive',
					statDeltas: { hp: 4 },
				},
				{
					id: 'war_cry_3',
					tier: 3,
					label: 'Unyielding',
					desc: '+2 DEF',
					type: 'passive',
					statDeltas: { def: 2 },
				},
			],
			BRUTAL_FORCE: [
				{
					id: 'war_bru_1',
					tier: 1,
					label: 'Heavy Cleave',
					desc: 'Brutal swing',
					type: 'active',
					element: 'PHYSICAL',
					targetType: 'enemy',
					mpCost: 0,
					mult: 1.4,
					subType: 'strike',
				},
				{
					id: 'war_bru_2',
					tier: 2,
					label: 'Shield Slam',
					desc: 'Knock frontline foe into rear',
					type: 'active',
					element: 'PHYSICAL',
					targetType: 'enemy',
					mpCost: 2,
					mult: 1.5,
					displacement: 'KNOCKBACK',
					subType: 'strike',
				},
				{
					id: 'war_bru_3',
					tier: 3,
					label: 'Ember Sunder',
					desc: 'Devastating hit',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 3,
					mult: 2.3,
					subType: 'strike',
					resonance: true,
				},
			],
		},
		MAGE: {
			DESTRUCTION: [
				{
					id: 'mag_des_1',
					tier: 1,
					label: 'Ember Bolt',
					desc: 'Fire bolt',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 4,
					power: 10,
					subType: 'bolt',
				},
				{
					id: 'mag_des_2',
					tier: 2,
					label: 'Flame Lance',
					desc: 'Fire lance',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 8,
					power: 16,
					subType: 'bolt',
				},
				{
					id: 'mag_des_3',
					tier: 3,
					label: 'Meteor Shard',
					desc: 'Heavy meteor',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 14,
					power: 24,
					subType: 'bolt',
				},
			],
			ARCANE_FOCUS: [
				{
					id: 'mag_arc_1',
					tier: 1,
					label: 'Channeling',
					desc: '+6 Max MP',
					type: 'passive',
					statDeltas: { mp: 6 },
				},
				{
					id: 'mag_arc_2',
					tier: 2,
					label: 'Arcane Sight',
					desc: '+2 AGI',
					type: 'passive',
					statDeltas: { agi: 2 },
				},
				{
					id: 'mag_arc_3',
					tier: 3,
					label: 'Leyline Mastery',
					desc: '+10 Max MP',
					type: 'passive',
					statDeltas: { mp: 10 },
				},
			],
			ELEMENTALISM: [
				{
					id: 'mag_ele_1',
					tier: 1,
					label: 'Flame Spark',
					desc: 'Fire spell',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 3,
					power: 10,
					subType: 'bolt',
				},
				{
					id: 'mag_ele_2',
					tier: 2,
					label: 'Frost Spike',
					desc: 'Ice spell',
					type: 'active',
					element: 'ICE',
					targetType: 'enemy',
					mpCost: 5,
					power: 16,
					subType: 'bolt',
				},
				{
					id: 'mag_ele_3',
					tier: 3,
					label: 'Inferno Orb',
					desc: 'High damage',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 8,
					power: 24,
					subType: 'bolt',
					resonance: true,
				},
			],
			PRIMAL_SURGE: [
				{
					id: 'mag_pri_1',
					tier: 1,
					label: 'Static Charge',
					desc: '+1 ATK',
					type: 'passive',
					statDeltas: { atk: 1 },
				},
				{
					id: 'mag_pri_2',
					tier: 2,
					label: 'Mana Shield',
					desc: '+2 DEF',
					type: 'passive',
					statDeltas: { def: 2 },
				},
				{
					id: 'mag_pri_3',
					tier: 3,
					label: 'Ember Nova',
					desc: 'Cataclysm burst',
					type: 'active',
					element: 'FIRE',
					targetType: 'enemy',
					mpCost: 12,
					power: 32,
					subType: 'bolt',
					resonance: true,
				},
			],
		},
		HEALER: {
			RESTORATION: [
				{
					id: 'hea_res_1',
					tier: 1,
					label: 'Minor Heal',
					desc: 'Restores HP',
					type: 'active',
					element: 'HOLY',
					targetType: 'ally',
					mpCost: 3,
					power: 10,
					subType: 'heal',
				},
				{
					id: 'hea_res_2',
					tier: 2,
					label: 'Greater Heal',
					desc: 'Large heal',
					type: 'active',
					element: 'HOLY',
					targetType: 'ally',
					mpCost: 6,
					power: 20,
					subType: 'heal',
				},
				{
					id: 'hea_res_3',
					tier: 3,
					label: 'Divine Grace',
					desc: 'Massive heal',
					type: 'active',
					element: 'HOLY',
					targetType: 'ally',
					mpCost: 10,
					power: 35,
					subType: 'heal',
					resonance: true,
				},
			],
			SANCTUARY: [
				{
					id: 'hea_san_1',
					tier: 1,
					label: 'Blessed Vigor',
					desc: '+4 Max HP',
					type: 'passive',
					statDeltas: { hp: 4 },
				},
				{
					id: 'hea_san_2',
					tier: 2,
					label: 'Serenity',
					desc: '+3 Max MP',
					type: 'passive',
					statDeltas: { mp: 3 },
				},
				{
					id: 'hea_san_3',
					tier: 3,
					label: 'Aegis',
					desc: '+2 DEF',
					type: 'passive',
					statDeltas: { def: 2 },
				},
			],
			SMITING: [
				{
					id: 'hea_smi_1',
					tier: 1,
					label: 'Smite',
					desc: 'Holy strike',
					type: 'active',
					element: 'HOLY',
					targetType: 'enemy',
					mpCost: 4,
					power: 8,
					subType: 'bolt',
					resonance: true,
				},
				{
					id: 'hea_smi_2',
					tier: 2,
					label: 'Righteous Fervor',
					desc: '+1 ATK',
					type: 'passive',
					statDeltas: { atk: 1 },
					resonance: true,
				},
				{
					id: 'hea_smi_3',
					tier: 3,
					label: 'Judgment',
					desc: 'Light blast',
					type: 'active',
					element: 'HOLY',
					targetType: 'enemy',
					mpCost: 10,
					power: 18,
					subType: 'bolt',
					resonance: true,
				},
			],
		},
	};

	const Progression = {
		AetherEssences,
		AetherNodes,
		SkillTrees,
	};

	if (typeof window !== 'undefined') {
		window._ManifestInternal.Progression = Progression;
	}
	if (typeof module !== 'undefined' && module.exports) {
		module.exports = Progression;
	}
})();
